In [1]:
import pandas as pd
import numpy as np

In [66]:
df=pd.read_csv('Admission_predict.csv')

In [3]:
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [4]:
#1  Display all rows where GRE Score is greater than 320.

df[df['GRE Score']>320]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
3,4,322,110,3,3.5,2.5,8.67,1,0.80
5,6,330,115,5,4.5,3.0,9.34,1,0.90
6,7,321,109,3,3.0,4.0,8.20,1,0.75
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [5]:
#2 Show applicants whose TOEFL Score is less than 100.

df[df['TOEFL Score']<100]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
27,28,298,98,2,1.5,2.5,7.50,1,0.44
28,29,295,93,1,2.0,2.0,7.20,0,0.46
29,30,310,99,2,1.5,2.0,7.30,0,0.54
30,31,300,97,2,3.0,3.0,8.10,1,0.65
50,51,313,98,3,2.5,4.5,8.30,1,0.76
57,58,298,99,2,4.0,2.0,7.60,0,0.46
58,59,300,99,1,3.0,2.0,6.80,1,0.36
77,78,301,99,2,3.0,2.0,8.22,0,0.64
78,79,296,95,2,3.0,2.0,7.54,1,0.44
79,80,294,93,1,1.5,2.0,7.36,0,0.46
91,92,299,97,3,5.0,3.5,7.66,0,0.38
92,93,298,98,2,4.0,3.0,8.03,0,0.34
93,94,301,97,2,3.0,3.0,7.88,1,0.44
94,95,303,99,3,2.0,2.5,7.66,0,0.36
118,119,296,99,2,3.0,3.5,7.28,0,0.47
161,162,298,99,1,1.5,3.0,7.46,0,0.53
168,169,293,97,2,2.0,4.0,7.80,1,0.64
169,170,311,99,2,2.5,3.0,7.98,0,0.65
205,206,295,99,2,2.5,3.0,7.65,0,0.57
206,207,315,99,2,3.5,3.0,7.89,0,0.63
225,226,296,99,2,2.5,2.5,8.03,0,0.61
251,252,316,99,2,2.5,3.0,9.00,0,0.70
256,257,309,99,3,4.0,4.0,8.56,0,0.76
271,272,299,96,2,1.5,2.0,7.86,0,0.54
272,273,294,95,1,1.5,1.5,7.64,0,0.49
273,274,312,99,1,1.0,1.5,8.01,1,0.52
292,293,302,99,2,1.0,2.0,7.97,0,0.56
293,294,312,98,1,3.5,3.0,8.18,1,0.64
317,318,300,99,1,1.0,2.5,8.01,0,0.58
329,330,297,96,2,2.5,1.5,7.89,0,0.43
344,345,295,96,2,1.5,2.0,7.34,0,0.47
345,346,316,98,1,1.5,2.0,7.43,0,0.49
346,347,304,97,2,1.5,2.0,7.64,0,0.47
347,348,299,94,1,1.0,1.0,7.34,0,0.42
348,349,302,99,1,2.0,2.0,7.25,0,0.57
354,355,297,98,2,2.5,3.0,7.67,0,0.59
367,368,311,98,1,1.0,2.5,7.46,0,0.57
368,369,298,92,1,2.0,2.0,7.88,0,0.51
369,370,301,98,1,2.0,3.0,8.03,1,0.67
376,377,297,96,2,2.5,2.0,7.43,0,0.34
378,379,303,98,1,2.0,2.5,7.65,0,0.56
379,380,311,99,1,2.5,3.0,8.43,1,0.71
388,389,296,97,2,1.5,2.0,7.80,0,0.49

In [6]:
#3 Get records where University Rating equals 5.

df[df['University Rating']==5]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
5,6,330,115,5,4.5,3.0,9.34,1,0.90
22,23,328,116,5,5.0,5.0,9.50,1,0.94
23,24,334,119,5,5.0,4.5,9.70,1,0.95
24,25,336,119,5,4.0,3.5,9.80,1,0.97
25,26,340,120,5,4.5,4.5,9.60,1,0.94
26,27,322,109,5,4.5,3.5,8.80,0,0.76
33,34,340,114,5,4.0,4.0,9.60,1,0.90
34,35,331,112,5,4.0,5.0,9.80,1,0.94
35,36,320,110,5,5.0,5.0,9.20,1,0.88
44,45,326,113,5,4.5,4.0,9.40,1,0.91
45,46,322,110,5,5.0,4.0,9.10,1,0.88
46,47,329,114,5,4.0,5.0,9.30,1,0.86
47,48,339,119,5,4.5,4.0,9.70,0,0.89
70,71,332,118,5,5.0,5.0,9.64,1,0.94
71,72,336,112,5,5.0,5.0,9.76,1,0.96
72,73,321,111,5,5.0,5.0,9.45,1,0.93
82,83,320,110,5,5.0,4.5,9.22,1,0.92
83,84,322,115,5,4.0,4.5,9.36,1,0.92
84,85,340,115,5,4.5,4.5,9.45,1,0.94
108,109,331,116,5,5.0,5.0,9.38,1,0.93
109,110,304,103,5,5.0,4.0,8.64,0,0.68
110,111,305,108,5,3.0,3.0,8.48,0,0.61
119,120,327,104,5,3.0,3.5,8.84,1,0.71
120,121,335,117,5,5.0,5.0,9.56,1,0.94
121,122,334,119,5,4.5,4.5,9.48,1,0.94
129,130,333,118,5,5.0,5.0,9.35,1,0.92
130,131,339,114,5,4.0,4.5,9.76,1,0.96
131,132,303,105,5,5.0,4.5,8.65,0,0.77
132,133,309,105,5,3.5,3.5,8.56,0,0.71
133,134,323,112,5,4.0,4.5,8.78,0,0.79
134,135,333,113,5,4.0,4.0,9.28,1,0.89
142,143,331,115,5,4.0,3.5,9.44,1,0.92
151,152,332,116,5,5.0,5.0,9.28,1,0.94
152,153,321,112,5,5.0,5.0,9.06,1,0.86
165,166,322,110,5,4.5,4.0,8.97,0,0.78
171,172,334,117,5,4.0,4.5,9.07,1,0.89
187,188,335,118,5,4.5,3.5,9.44,1,0.93
188,189,331,115,5,4.5,3.5,9.36,1,0.93
189,190,324,112,5,5.0,5.0,9.08,1,0.88
190,191,324,111,5,4.5,4.0,9.16,1,0.90
191,192,323,110,5,4.0,5.0,8.98,1,0.87
192,193,322,114,5,4.5,4.0,8.94,1,0.86
193,194,336,118,5,4.5,5.0,9.53,1,0.94
202,203,340,120,5,4.5,4.5,9.91,1,0.97
203,204,334,120,5,4.0,5.0,9.87,1,0.97
213,214,333,119,5,5.0,4.5,9.78,1,0.96
215,216,330,116,5,5.0,4.5,9.36,1,0.93
234,235,330,113,5,5.0,4.0,9.31,1,0.91
235,236,326,111,5,4.5,4.0,9.23,1,0.88
237,238,329,114,5,4.5,5.0,9.19,1,0.86
260,261,327,108,5,5.0,3.5,9.13,1,0.87
276,277,329,113,5,5.0,4.5,9.45,1,0.89
285,286,331,116,5,4.0,4.0,9.26,1,0.93
286,287,336,118,5,4.5,4.0,9.19,1,0.92
287,288,324,114,5,5.0,4.5,9.08,1,0.89
337,338,332,118,5,5.0,5.0,9.47,1,0.94
338,339,323,108,5,4.0,4.0,8.74,1,0.81
339,340,324,107,5,3.5,4.0,8.66,1,0.81
362,363,338,115,5,4.5,5.0,9.23,1,0.91
385,386,335,117,5,5.0,5.0,9.82,1,0.96

In [7]:
#4 Select all students who have done Research (value 1).

df[df['Research']==1]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
5,6,330,115,5,4.5,3.0,9.34,1,0.90
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [8]:
#5 Display students who have not done Research (value 0).

df[df['Research']==0]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
4,5,314,103,2,2.0,3.0,8.21,0,0.65
7,8,308,101,2,3.0,4.0,7.90,0,0.68
8,9,302,102,1,2.0,1.5,8.00,0,0.50
9,10,323,108,3,3.5,3.0,8.60,0,0.45
15,16,314,105,3,3.5,2.5,8.30,0,0.54
...,...,...,...,...,...,...,...,...,...
388,389,296,97,2,1.5,2.0,7.80,0,0.49
390,391,314,102,2,2.0,2.5,8.24,0,0.64
391,392,318,106,3,2.0,3.0,8.65,0,0.71
393,394,317,104,2,3.0,3.0,8.76,0,0.77
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [9]:
#6 Find applicants with CGPA greater than 9.0.

df[df['CGPA']>9]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
5,6,330,115,5,4.5,3.0,9.34,1,0.90
12,13,328,112,4,4.0,4.5,9.10,1,0.78
22,23,328,116,5,5.0,5.0,9.50,1,0.94
23,24,334,119,5,5.0,4.5,9.70,1,0.95
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [10]:
#7 Retrieve records where both GRE Score> 320 and CGPA > 9.0.

df[(df['GRE Score']>320)&(df['TOEFL Score']>9)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
3,4,322,110,3,3.5,2.5,8.67,1,0.80
5,6,330,115,5,4.5,3.0,9.34,1,0.90
6,7,321,109,3,3.0,4.0,8.20,1,0.75
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [11]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [12]:
#8 Display records where either SOP or LOR rating is 5.0.

df[(df['SOP']==5)|(df['LOR ']==5)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
22,23,328,116,5,5.0,5.0,9.50,1,0.94
23,24,334,119,5,5.0,4.5,9.70,1,0.95
34,35,331,112,5,4.0,5.0,9.80,1,0.94
35,36,320,110,5,5.0,5.0,9.20,1,0.88
45,46,322,110,5,5.0,4.0,9.10,1,0.88
46,47,329,114,5,4.0,5.0,9.30,1,0.86
48,49,321,110,3,3.5,5.0,8.85,1,0.82
70,71,332,118,5,5.0,5.0,9.64,1,0.94
71,72,336,112,5,5.0,5.0,9.76,1,0.96
72,73,321,111,5,5.0,5.0,9.45,1,0.93
74,75,314,106,3,3.0,5.0,8.90,0,0.74
81,82,340,120,4,5.0,5.0,9.50,1,0.96
82,83,320,110,5,5.0,4.5,9.22,1,0.92
91,92,299,97,3,5.0,3.5,7.66,0,0.38
98,99,332,119,4,5.0,4.5,9.24,1,0.90
108,109,331,116,5,5.0,5.0,9.38,1,0.93
109,110,304,103,5,5.0,4.0,8.64,0,0.68
120,121,335,117,5,5.0,5.0,9.56,1,0.94
129,130,333,118,5,5.0,5.0,9.35,1,0.92
131,132,303,105,5,5.0,4.5,8.65,0,0.77
136,137,312,103,3,5.0,4.0,8.45,0,0.76
151,152,332,116,5,5.0,5.0,9.28,1,0.94
152,153,321,112,5,5.0,5.0,9.06,1,0.86
166,167,302,102,3,3.5,5.0,8.33,0,0.65
172,173,322,110,4,4.0,5.0,9.13,1,0.86
189,190,324,112,5,5.0,5.0,9.08,1,0.88
191,192,323,110,5,4.0,5.0,8.98,1,0.87
193,194,336,118,5,4.5,5.0,9.53,1,0.94
203,204,334,120,5,4.0,5.0,9.87,1,0.97
211,212,328,110,4,5.0,4.0,9.14,1,0.82
212,213,338,120,4,5.0,5.0,9.66,1,0.95
213,214,333,119,5,5.0,4.5,9.78,1,0.96
214,215,331,117,4,4.5,5.0,9.42,1,0.94
215,216,330,116,5,5.0,4.5,9.36,1,0.93
234,235,330,113,5,5.0,4.0,9.31,1,0.91
237,238,329,114,5,4.5,5.0,9.19,1,0.86
254,255,321,114,4,4.0,5.0,9.12,0,0.85
257,258,324,100,3,4.0,5.0,8.64,1,0.78
258,259,326,102,4,5.0,5.0,8.76,1,0.77
259,260,331,119,4,5.0,4.5,9.34,1,0.90
260,261,327,108,5,5.0,3.5,9.13,1,0.87
268,269,327,113,4,4.5,5.0,9.14,0,0.83
269,270,308,108,4,4.5,5.0,8.34,0,0.77
276,277,329,113,5,5.0,4.5,9.45,1,0.89
284,285,340,112,4,5.0,4.5,9.66,1,0.94
287,288,324,114,5,5.0,4.5,9.08,1,0.89
288,289,314,104,4,5.0,5.0,9.02,0,0.82
337,338,332,118,5,5.0,5.0,9.47,1,0.94
360,361,322,110,3,4.0,5.0,8.64,1,0.85
362,363,338,115,5,4.5,5.0,9.23,1,0.91
384,385,340,113,4,5.0,5.0,9.74,1,0.96
385,386,335,117,5,5.0,5.0,9.82,1,0.96
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [13]:
#9 Get rows where Chance of Admit is above 0.8 and University Rating ≥ 4.

df[(df['Chance of Admit ']>0.8)&(df['University Rating']>=4)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
5,6,330,115,5,4.5,3.0,9.34,1,0.90
11,12,327,111,4,4.0,4.5,9.00,1,0.84
22,23,328,116,5,5.0,5.0,9.50,1,0.94
23,24,334,119,5,5.0,4.5,9.70,1,0.95
...,...,...,...,...,...,...,...,...,...
385,386,335,117,5,5.0,5.0,9.82,1,0.96
392,393,326,112,4,4.0,3.5,9.12,1,0.84
394,395,329,111,4,4.5,4.0,9.23,1,0.89
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [14]:
#10 Find all rows where TOEFL Score is between 100 and 110.

df[(df['TOEFL Score']>100)&(df['TOEFL Score']<110)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
4,5,314,103,2,2.0,3.0,8.21,0,0.65
6,7,321,109,3,3.0,4.0,8.20,1,0.75
7,8,308,101,2,3.0,4.0,7.90,0,0.68
...,...,...,...,...,...,...,...,...,...
390,391,314,102,2,2.0,2.5,8.24,0,0.64
391,392,318,106,3,2.0,3.0,8.65,0,0.71
393,394,317,104,2,3.0,3.0,8.76,0,0.77
396,397,325,107,3,3.0,3.5,9.11,1,0.84
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [15]:
#11 Display data for students whose GRE Score is not equal to 300.
df[df['GRE Score']!=300]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [16]:
#12 Show all students with CGPA less than 8 and Research = 1.

df[(df['CGPA']<8)&(df['Research']==1)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
20,21,312,107,3,3.0,2.0,7.90,1,0.64
27,28,298,98,2,1.5,2.5,7.50,1,0.44
51,52,312,100,2,1.5,3.5,7.90,1,0.56
58,59,300,99,1,3.0,2.0,6.80,1,0.36
78,79,296,95,2,3.0,2.0,7.54,1,0.44
90,91,318,106,2,4.0,4.0,7.92,1,0.64
93,94,301,97,2,3.0,3.0,7.88,1,0.44
168,169,293,97,2,2.0,4.0,7.80,1,0.64
357,358,301,104,2,3.5,3.5,7.89,1,0.68

In [17]:
#13 Retrieve rows where University Rating < 3 and SOP > 4.

df[(df['University Rating']<3)&(df['SOP']>4)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
103,104,317,104,2,4.5,4.0,8.47,0,0.57
138,139,326,116,2,4.5,3.0,9.08,1,0.80
141,142,332,118,2,4.5,3.5,9.36,1,0.90

In [18]:
#14 Get records of students having TOEFL Score > 105 but GRE Score< 310.

df[(df['TOEFL Score']>105)&(df['GRE Score']<310)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
13,14,307,109,3,4.0,3.0,8.00,1,0.62
36,37,299,106,2,4.0,4.0,8.40,0,0.64
39,40,307,108,2,4.0,3.5,7.70,0,0.48
40,41,308,110,3,3.5,3.0,8.00,1,0.46
110,111,305,108,5,3.0,3.0,8.48,0,0.61
112,113,301,107,3,3.5,3.5,8.34,1,0.62
123,124,308,108,3,3.5,3.5,8.22,0,0.61
124,125,301,106,4,2.5,3.0,8.47,0,0.57
158,159,306,106,2,2.0,2.5,8.14,0,0.61
178,179,309,108,3,2.5,3.0,8.12,0,0.72
181,182,305,107,2,2.5,2.5,8.42,0,0.71
195,196,307,107,2,3.0,3.5,8.52,1,0.78
208,209,305,106,2,3.0,3.0,8.16,0,0.64
223,224,308,109,2,3.0,4.0,8.45,0,0.71
226,227,306,110,2,3.5,4.0,8.45,0,0.63
255,256,307,110,4,4.0,4.5,8.37,0,0.79
269,270,308,108,4,4.5,5.0,8.34,0,0.77
299,300,305,112,3,3.0,3.5,8.65,0,0.71
300,301,309,106,2,2.5,2.5,8.00,0,0.62
309,310,308,110,4,3.5,3.0,8.60,0,0.70
332,333,308,106,3,3.5,2.5,8.21,1,0.75
342,343,308,106,3,3.0,3.0,8.24,0,0.58

In [19]:
#15 Display records where Chance of Admit < 0.6 or GRE Score > 300.

df[(df['Chance of Admit ']<0.6)|(df['GRE Score']>300)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [20]:
#16 Find the top 10 students with the highest GRE Score.
df.sort_values(['GRE Score'],ascending=False).head(10)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
202,203,340,120,5,4.5,4.5,9.91,1,0.97
33,34,340,114,5,4.0,4.0,9.60,1,0.90
84,85,340,115,5,4.5,4.5,9.45,1,0.94
143,144,340,120,4,4.5,4.0,9.92,1,0.97
81,82,340,120,4,5.0,5.0,9.50,1,0.96
284,285,340,112,4,5.0,4.5,9.66,1,0.94
25,26,340,120,5,4.5,4.5,9.60,1,0.94
384,385,340,113,4,5.0,5.0,9.74,1,0.96
47,48,339,119,5,4.5,4.0,9.70,0,0.89
130,131,339,114,5,4.0,4.5,9.76,1,0.96

In [21]:
#17 Display applicants who scored exactly 4.5 in LOR.
df[df['LOR ']==4.5]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
11,12,327,111,4,4.0,4.5,9.00,1,0.84
12,13,328,112,4,4.0,4.5,9.10,1,0.78
23,24,334,119,5,5.0,4.5,9.70,1,0.95
25,26,340,120,5,4.5,4.5,9.60,1,0.94
32,33,338,118,4,3.0,4.5,9.40,1,0.91
50,51,313,98,3,2.5,4.5,8.30,1,0.76
82,83,320,110,5,5.0,4.5,9.22,1,0.92
83,84,322,115,5,4.0,4.5,9.36,1,0.92
84,85,340,115,5,4.5,4.5,9.45,1,0.94
98,99,332,119,4,5.0,4.5,9.24,1,0.90
105,106,316,110,3,4.0,4.5,8.78,1,0.69
106,107,329,111,4,4.5,4.5,9.18,1,0.87
107,108,338,117,4,3.5,4.5,9.46,1,0.91
115,116,310,106,4,4.5,4.5,9.04,1,0.66
121,122,334,119,5,4.5,4.5,9.48,1,0.94
130,131,339,114,5,4.0,4.5,9.76,1,0.96
131,132,303,105,5,5.0,4.5,8.65,0,0.77
133,134,323,112,5,4.0,4.5,8.78,0,0.79
171,172,334,117,5,4.0,4.5,9.07,1,0.89
173,174,323,113,4,4.0,4.5,9.23,1,0.89
176,177,329,119,4,4.5,4.5,9.16,1,0.90
185,186,327,113,4,4.5,4.5,9.11,1,0.89
198,199,311,104,3,4.5,4.5,8.43,0,0.70
199,200,313,107,3,4.0,4.5,8.69,0,0.72
202,203,340,120,5,4.5,4.5,9.91,1,0.97
213,214,333,119,5,5.0,4.5,9.78,1,0.96
215,216,330,116,5,5.0,4.5,9.36,1,0.93
216,217,322,112,4,4.5,4.5,9.26,1,0.91
230,231,313,104,3,4.0,4.5,8.65,0,0.73
236,237,325,112,4,4.0,4.5,9.17,1,0.85
253,254,335,115,4,4.5,4.5,9.68,1,0.93
255,256,307,110,4,4.0,4.5,8.37,0,0.79
259,260,331,119,4,5.0,4.5,9.34,1,0.90
276,277,329,113,5,5.0,4.5,9.45,1,0.89
281,282,317,110,3,4.0,4.5,9.11,1,0.80
284,285,340,112,4,5.0,4.5,9.66,1,0.94
287,288,324,114,5,5.0,4.5,9.08,1,0.89
297,298,320,120,3,4.0,4.5,9.11,0,0.86
298,299,330,114,3,4.5,4.5,9.24,1,0.90
312,313,311,107,4,4.5,4.5,9.00,1,0.78
335,336,325,111,4,4.0,4.5,9.11,1,0.83
366,367,320,104,3,3.5,4.5,8.34,1,0.74
397,398,330,116,4,5.0,4.5,9.45,1,0.91

In [22]:
#18 Select students whose SOP rating lies between 3 and 4 (inclusive).

df[df['SOP'].between(3, 4, inclusive='both')]
#df[(df['SOP']>=3)&(df['SOP']<=4)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
6,7,321,109,3,3.0,4.0,8.20,1,0.75
7,8,308,101,2,3.0,4.0,7.90,0,0.68
...,...,...,...,...,...,...,...,...,...
392,393,326,112,4,4.0,3.5,9.12,1,0.84
393,394,317,104,2,3.0,3.0,8.76,0,0.77
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [23]:
#19  Display all students whose University Rating is either 2 or 3.

df[(df['University Rating']==2)|(df['University Rating']==3)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
6,7,321,109,3,3.0,4.0,8.20,1,0.75
7,8,308,101,2,3.0,4.0,7.90,0,0.68
...,...,...,...,...,...,...,...,...,...
391,392,318,106,3,2.0,3.0,8.65,0,0.71
393,394,317,104,2,3.0,3.0,8.76,0,0.77
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [24]:
#20 Filter rows where CGPA is an integer value (e.g., 8.0, 9.0).

df[df['CGPA']%1==0]
#df[df['CGPA']==df['CGPA'].astype('int')]
#df[df['CGPA']//1==df['CGPA']]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
2,3,316,104,3,3.0,3.5,8.0,1,0.72
8,9,302,102,1,2.0,1.5,8.0,0,0.50
11,12,327,111,4,4.0,4.5,9.0,1,0.84
13,14,307,109,3,4.0,3.0,8.0,1,0.62
17,18,319,106,3,4.0,3.0,8.0,1,0.65
40,41,308,110,3,3.5,3.0,8.0,1,0.46
52,53,334,116,4,4.0,3.0,8.0,1,0.78
54,55,322,110,3,3.0,3.5,8.0,0,0.70
96,97,306,100,2,3.0,3.0,8.0,0,0.48
251,252,316,99,2,2.5,3.0,9.0,0,0.70
289,290,313,109,3,4.0,3.5,9.0,0,0.79
300,301,309,106,2,2.5,2.5,8.0,0,0.62
307,308,325,112,4,4.0,4.0,9.0,1,0.80
312,313,311,107,4,4.5,4.5,9.0,1,0.78

In [25]:
#21 Retrieve records where Chance of Admit is between 0.5 and 0.7.

df[df['Chance of Admit '].between(0.5,0.7)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
4,5,314,103,2,2.0,3.0,8.21,0,0.65
7,8,308,101,2,3.0,4.0,7.90,0,0.68
8,9,302,102,1,2.0,1.5,8.00,0,0.50
10,11,325,106,3,3.5,4.0,8.40,1,0.52
13,14,307,109,3,4.0,3.0,8.00,1,0.62
...,...,...,...,...,...,...,...,...,...
378,379,303,98,1,2.0,2.5,7.65,0,0.56
383,384,300,100,3,3.0,3.5,8.26,0,0.62
387,388,307,105,2,2.0,3.5,8.10,0,0.53
390,391,314,102,2,2.0,2.5,8.24,0,0.64
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [26]:
#22 Select students who scored below average GRE Score.

a=df['GRE Score'].mean()
df[df['GRE Score']<a]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
2,3,316,104,3,3.0,3.5,8.00,1,0.72
4,5,314,103,2,2.0,3.0,8.21,0,0.65
7,8,308,101,2,3.0,4.0,7.90,0,0.68
8,9,302,102,1,2.0,1.5,8.00,0,0.50
13,14,307,109,3,4.0,3.0,8.00,1,0.62
...,...,...,...,...,...,...,...,...,...
386,387,302,101,2,2.5,3.5,7.96,0,0.46
387,388,307,105,2,2.0,3.5,8.10,0,0.53
388,389,296,97,2,1.5,2.0,7.80,0,0.49
390,391,314,102,2,2.0,2.5,8.24,0,0.64
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [27]:
#23 Show all records where TOEFL Score equals the dataset’s maximum TOEFL Score.
a=df['TOEFL Score'].max()
df[df['TOEFL Score']==a]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
25,26,340,120,5,4.5,4.5,9.60,1,0.94
81,82,340,120,4,5.0,5.0,9.50,1,0.96
97,98,331,120,3,4.0,4.0,8.96,1,0.86
143,144,340,120,4,4.5,4.0,9.92,1,0.97
202,203,340,120,5,4.5,4.5,9.91,1,0.97
203,204,334,120,5,4.0,5.0,9.87,1,0.97
212,213,338,120,4,5.0,5.0,9.66,1,0.95
297,298,320,120,3,4.0,4.5,9.11,0,0.86

In [28]:
#24 Filter students who have both LOR and SOP less than 3.

df[(df['LOR ']<3)&(df['SOP']<3)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
8,9,302,102,1,2.0,1.5,8.00,0,0.50
27,28,298,98,2,1.5,2.5,7.50,1,0.44
28,29,295,93,1,2.0,2.0,7.20,0,0.46
29,30,310,99,2,1.5,2.0,7.30,0,0.54
37,38,300,105,1,1.0,2.0,7.80,0,0.58
...,...,...,...,...,...,...,...,...,...
376,377,297,96,2,2.5,2.0,7.43,0,0.34
377,378,290,100,1,1.5,2.0,7.56,0,0.47
378,379,303,98,1,2.0,2.5,7.65,0,0.56
388,389,296,97,2,1.5,2.0,7.80,0,0.49
390,391,314,102,2,2.0,2.5,8.24,0,0.64

In [29]:
#25 Retrieve students who have GRE Score divisible by 5.

df[df['GRE Score']%5==0]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
5,6,330,115,5,4.5,3.0,9.34,1,0.90
10,11,325,106,3,3.5,4.0,8.40,1,0.52
21,22,325,114,4,3.0,2.0,8.40,0,0.70
25,26,340,120,5,4.5,4.5,9.60,1,0.94
28,29,295,93,1,2.0,2.0,7.20,0,0.46
...,...,...,...,...,...,...,...,...,...
384,385,340,113,4,5.0,5.0,9.74,1,0.96
385,386,335,117,5,5.0,5.0,9.82,1,0.96
389,390,320,108,3,3.5,4.0,8.44,1,0.76
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91

In [30]:
#26 Add a new column named GRE_to_TOEFL_Ratio = GRE Score / TOEFL Score.

df['GRE_to_TOEFL_Ratio']=df['GRE Score']/df['TOEFL Score']
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit,GRE_to_TOEFL_Ratio
0,1,337,118,4,4.5,4.5,9.65,1,0.92,2.855932
1,2,324,107,4,4.0,4.5,8.87,1,0.76,3.028037
2,3,316,104,3,3.0,3.5,8.00,1,0.72,3.038462
3,4,322,110,3,3.5,2.5,8.67,1,0.80,2.927273
4,5,314,103,2,2.0,3.0,8.21,0,0.65,3.048544
...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82,2.945455
396,397,325,107,3,3.0,3.5,9.11,1,0.84,3.037383
397,398,330,116,4,5.0,4.5,9.45,1,0.91,2.844828
398,399,312,103,3,3.5,4.0,8.78,0,0.67,3.029126
399,400,333,117,4,5.0,4.0,9.66,1,0.95,2.846154

In [31]:
#27 Create a new column Admission_Chance_% = Chance of Admit × 100.

df['Admission_Chance_%']=df['Chance of Admit ']*100
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit,GRE_to_TOEFL_Ratio,Admission_Chance_%
0,1,337,118,4,4.5,4.5,9.65,1,0.92,2.855932,92.0
1,2,324,107,4,4.0,4.5,8.87,1,0.76,3.028037,76.0
2,3,316,104,3,3.0,3.5,8.00,1,0.72,3.038462,72.0
3,4,322,110,3,3.5,2.5,8.67,1,0.80,2.927273,80.0
4,5,314,103,2,2.0,3.0,8.21,0,0.65,3.048544,65.0
...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82,2.945455,82.0
396,397,325,107,3,3.0,3.5,9.11,1,0.84,3.037383,84.0
397,398,330,116,4,5.0,4.5,9.45,1,0.91,2.844828,91.0
398,399,312,103,3,3.5,4.0,8.78,0,0.67,3.029126,67.0
399,400,333,117,4,5.0,4.0,9.66,1,0.95,2.846154,95.0

In [32]:
#28 Rename the column Chance of Admit to Admit_Probability.

df=df.rename(columns={'Admission_Chance_%':'Admit_Probability'})

In [33]:
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit,GRE_to_TOEFL_Ratio,Admit_Probability
0,1,337,118,4,4.5,4.5,9.65,1,0.92,2.855932,92.0
1,2,324,107,4,4.0,4.5,8.87,1,0.76,3.028037,76.0
2,3,316,104,3,3.0,3.5,8.00,1,0.72,3.038462,72.0
3,4,322,110,3,3.5,2.5,8.67,1,0.80,2.927273,80.0
4,5,314,103,2,2.0,3.0,8.21,0,0.65,3.048544,65.0
...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82,2.945455,82.0
396,397,325,107,3,3.0,3.5,9.11,1,0.84,3.037383,84.0
397,398,330,116,4,5.0,4.5,9.45,1,0.91,2.844828,91.0
398,399,312,103,3,3.5,4.0,8.78,0,0.67,3.029126,67.0
399,400,333,117,4,5.0,4.0,9.66,1,0.95,2.846154,95.0

In [34]:
#29 Change all column names to lowercase.

df.columns=df.columns.str.lower()

In [35]:
df

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,admit_probability
0,1,337,118,4,4.5,4.5,9.65,1,0.92,2.855932,92.0
1,2,324,107,4,4.0,4.5,8.87,1,0.76,3.028037,76.0
2,3,316,104,3,3.0,3.5,8.00,1,0.72,3.038462,72.0
3,4,322,110,3,3.5,2.5,8.67,1,0.80,2.927273,80.0
4,5,314,103,2,2.0,3.0,8.21,0,0.65,3.048544,65.0
...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82,2.945455,82.0
396,397,325,107,3,3.0,3.5,9.11,1,0.84,3.037383,84.0
397,398,330,116,4,5.0,4.5,9.45,1,0.91,2.844828,91.0
398,399,312,103,3,3.5,4.0,8.78,0,0.67,3.029126,67.0
399,400,333,117,4,5.0,4.0,9.66,1,0.95,2.846154,95.0

In [36]:
#30 Drop the column Serial No..
#df=df.drop(columns=['serial no.'])
df

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,admit_probability
0,1,337,118,4,4.5,4.5,9.65,1,0.92,2.855932,92.0
1,2,324,107,4,4.0,4.5,8.87,1,0.76,3.028037,76.0
2,3,316,104,3,3.0,3.5,8.00,1,0.72,3.038462,72.0
3,4,322,110,3,3.5,2.5,8.67,1,0.80,2.927273,80.0
4,5,314,103,2,2.0,3.0,8.21,0,0.65,3.048544,65.0
...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82,2.945455,82.0
396,397,325,107,3,3.0,3.5,9.11,1,0.84,3.037383,84.0
397,398,330,116,4,5.0,4.5,9.45,1,0.91,2.844828,91.0
398,399,312,103,3,3.5,4.0,8.78,0,0.67,3.029126,67.0
399,400,333,117,4,5.0,4.0,9.66,1,0.95,2.846154,95.0

In [37]:
#31 Round all values in CGPA to one decimal place.
df['cgpa']=df['cgpa'].round(1)

In [38]:
#32 Replace all University Rating values of 5 with 10.
df['university rating']=df['university rating'].replace(5,10)

In [39]:
#33 Convert Research column values from 0/1 to “No”/“Yes”.

df['research']=df['research'].apply(lambda x:'yes' if x==1 else 'no')

In [40]:
#34 Create a new column GRE_Level = “High” if GRE ≥ 320 else “Low”.
df['GRE_Level']=df['gre score'].apply(lambda x:'High' if x>=320 else 'Low')

In [41]:
#35 Normalize CGPA column to range 0–1 using min-max scaling (without sklearn).

#normalise by min&max formula= (x-xmin)/(xmax-xmin)

df['normalize gpa']=(df['cgpa']-df['cgpa'].min())/((df['cgpa'].max())-(df['cgpa'].min()))

In [42]:
#36 Increase all TOEFL Score values by 2 points.

df['toefl score']=df['toefl score']+2

In [43]:
#38 add a column weighted_score=gre score*0.3+toefl score*0.2+cgpa*0.5

df['Weighted_score']=df['gre score']*.3+df['toefl score']*0.2+df['cgpa']*0.5

In [44]:
df

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,admit_probability,GRE_Level,normalize gpa,Weighted_score
0,1,337,120,4,4.5,4.5,9.6,yes,0.92,2.855932,92.0,High,0.903226,129.90
1,2,324,109,4,4.0,4.5,8.9,yes,0.76,3.028037,76.0,High,0.677419,123.45
2,3,316,106,3,3.0,3.5,8.0,yes,0.72,3.038462,72.0,Low,0.387097,120.00
3,4,322,112,3,3.5,2.5,8.7,yes,0.80,2.927273,80.0,High,0.612903,123.35
4,5,314,105,2,2.0,3.0,8.2,no,0.65,3.048544,65.0,Low,0.451613,119.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,yes,0.82,2.945455,82.0,High,0.709677,124.10
396,397,325,109,3,3.0,3.5,9.1,yes,0.84,3.037383,84.0,High,0.741935,123.85
397,398,330,118,4,5.0,4.5,9.4,yes,0.91,2.844828,91.0,High,0.838710,127.30
398,399,312,105,3,3.5,4.0,8.8,no,0.67,3.029126,67.0,Low,0.645161,119.00
399,400,333,119,4,5.0,4.0,9.7,yes,0.95,2.846154,95.0,High,0.935484,128.55

In [45]:
#39 Drop all duplicated rows if any
df.duplicated().sum()

0

In [66]:
#40 replace all sop values less than 2 with the mean sop

#df.loc[df['sop']<2,'sop']=df['sop'].mean()
df.loc[df['SOP'] < 2, 'SOP'] = df['SOP'].mean()

In [48]:
df

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,admit_probability,GRE_Level,normalize gpa,Weighted_score
0,1,337,120,4,4.5,4.5,9.6,yes,0.92,2.855932,92.0,High,0.903226,129.90
1,2,324,109,4,4.0,4.5,8.9,yes,0.76,3.028037,76.0,High,0.677419,123.45
2,3,316,106,3,3.0,3.5,8.0,yes,0.72,3.038462,72.0,Low,0.387097,120.00
3,4,322,112,3,3.5,2.5,8.7,yes,0.80,2.927273,80.0,High,0.612903,123.35
4,5,314,105,2,2.0,3.0,8.2,no,0.65,3.048544,65.0,Low,0.451613,119.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,yes,0.82,2.945455,82.0,High,0.709677,124.10
396,397,325,109,3,3.0,3.5,9.1,yes,0.84,3.037383,84.0,High,0.741935,123.85
397,398,330,118,4,5.0,4.5,9.4,yes,0.91,2.844828,91.0,High,0.838710,127.30
398,399,312,105,3,3.5,4.0,8.8,no,0.67,3.029126,67.0,Low,0.645161,119.00
399,400,333,119,4,5.0,4.0,9.7,yes,0.95,2.846154,95.0,High,0.935484,128.55

In [67]:
#41 crete a new column combining universiyy rating and research (eg.. 'Rating - research')

df['rating_research'] = df['University Rating'].astype(str) + ' - ' + df['Research'].astype(str)

In [81]:
#df=df.drop(columns=['rr'])
df

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,rating_research,admit_probability
0,1,337,118,4,4.5,4.5,9.6,1,0.92,4 - 1,92.0
1,2,324,107,4,4.0,4.5,8.9,1,0.76,4 - 1,76.0
2,3,316,104,3,3.0,3.5,8.0,1,0.72,3 - 1,72.0
3,4,322,110,3,3.5,2.5,8.7,1,0.80,3 - 1,80.0
4,5,314,103,2,2.0,3.0,8.2,0,0.65,2 - 0,65.0
...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.0,1,0.82,3 - 1,82.0
396,397,325,107,3,3.0,3.5,9.1,1,0.84,3 - 1,84.0
397,398,330,116,4,5.0,4.5,9.4,1,0.91,4 - 1,91.0
398,399,312,103,3,3.5,4.0,8.8,0,0.67,3 - 0,67.0
399,400,333,117,4,5.0,4.0,9.7,1,0.95,4 - 1,95.0

In [82]:
#42 convert chanse of admit to categorial bins:'Low','Medium','High'

df['admit chance']=pd.cut(
    df['admit_probability'],
    bins=[0,40,75,100],
    labels=['Low','Mid','High']
)

In [83]:
df

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,rating_research,admit_probability,admit chance
0,1,337,118,4,4.5,4.5,9.6,1,0.92,4 - 1,92.0,High
1,2,324,107,4,4.0,4.5,8.9,1,0.76,4 - 1,76.0,High
2,3,316,104,3,3.0,3.5,8.0,1,0.72,3 - 1,72.0,Mid
3,4,322,110,3,3.5,2.5,8.7,1,0.80,3 - 1,80.0,High
4,5,314,103,2,2.0,3.0,8.2,0,0.65,2 - 0,65.0,Mid
...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.0,1,0.82,3 - 1,82.0,High
396,397,325,107,3,3.0,3.5,9.1,1,0.84,3 - 1,84.0,High
397,398,330,116,4,5.0,4.5,9.4,1,0.91,4 - 1,91.0,High
398,399,312,103,3,3.5,4.0,8.8,0,0.67,3 - 0,67.0,Mid
399,400,333,117,4,5.0,4.0,9.7,1,0.95,4 - 1,95.0,High

In [84]:
#43 add a constant column Country with value is India

df['Country']='India'

In [86]:
#44 Reorder columns so that chance of Admit comes first

first = ['admit chance']
others = [col for col in df.columns if col != 'admit chance']

df = df[first + others]

In [87]:
df

,admit chance,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,rating_research,admit_probability,Country
0,High,1,337,118,4,4.5,4.5,9.6,1,0.92,4 - 1,92.0,India
1,High,2,324,107,4,4.0,4.5,8.9,1,0.76,4 - 1,76.0,India
2,Mid,3,316,104,3,3.0,3.5,8.0,1,0.72,3 - 1,72.0,India
3,High,4,322,110,3,3.5,2.5,8.7,1,0.80,3 - 1,80.0,India
4,Mid,5,314,103,2,2.0,3.0,8.2,0,0.65,2 - 0,65.0,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,High,396,324,110,3,3.5,3.5,9.0,1,0.82,3 - 1,82.0,India
396,High,397,325,107,3,3.0,3.5,9.1,1,0.84,3 - 1,84.0,India
397,High,398,330,116,4,5.0,4.5,9.4,1,0.91,4 - 1,91.0,India
398,Mid,399,312,103,3,3.5,4.0,8.8,0,0.67,3 - 0,67.0,India
399,High,400,333,117,4,5.0,4.0,9.7,1,0.95,4 - 1,95.0,India

In [89]:
#45 replace values in LOR column where reting is 5 with 4.9

df['lor ']=df['lor '].replace(5,4.9)

In [60]:
#46 convert all float columns to integers (after rounding)

df = df.round(0)
df = df.astype({col: 'int' for col in df.select_dtypes(include=['float']).columns})

In [90]:
### 47 replace CGPA values above 9.5 eith 9.5

df.loc[df['cgpa']>9.5,'cgpa']=9.5

In [91]:
 #48 apply lambda function to square all sop values

df['ssop']=df['sop'].apply(lambda x: x**2)
df

,admit chance,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,rating_research,admit_probability,Country,ssop
0,High,1,337,118,4,4.5,4.5,9.5,1,0.92,4 - 1,92.0,India,20.25
1,High,2,324,107,4,4.0,4.5,8.9,1,0.76,4 - 1,76.0,India,16.00
2,Mid,3,316,104,3,3.0,3.5,8.0,1,0.72,3 - 1,72.0,India,9.00
3,High,4,322,110,3,3.5,2.5,8.7,1,0.80,3 - 1,80.0,India,12.25
4,Mid,5,314,103,2,2.0,3.0,8.2,0,0.65,2 - 0,65.0,India,4.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,High,396,324,110,3,3.5,3.5,9.0,1,0.82,3 - 1,82.0,India,12.25
396,High,397,325,107,3,3.0,3.5,9.1,1,0.84,3 - 1,84.0,India,9.00
397,High,398,330,116,4,5.0,4.5,9.4,1,0.91,4 - 1,91.0,India,25.00
398,Mid,399,312,103,3,3.5,4.0,8.8,0,0.67,3 - 0,67.0,India,12.25
399,High,400,333,117,4,5.0,4.0,9.5,1,0.95,4 - 1,95.0,India,25.00

In [93]:
#49 find mean of CGPA with and with out reaserch

a=df[df['research']==1]['cgpa'].mean()
b=df[df['research']==0]['cgpa'].mean()
a,b

(8.857534246575343, 8.255801104972377)

In [95]:
#50 Add a column GRE_Category = “Below Avg”, “Avg”, “Above Avg” based on mean GRE.

df['gre_cat']=pd.cut(
    df['gre score'],
    bins=[290,300,315,340],
    labels=['Below Avg', 'Avg', 'Above Avg']
)

In [96]:
df

,admit chance,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,rating_research,admit_probability,Country,ssop,gre_cat
0,High,1,337,118,4,4.5,4.5,9.5,1,0.92,4 - 1,92.0,India,20.25,Above Avg
1,High,2,324,107,4,4.0,4.5,8.9,1,0.76,4 - 1,76.0,India,16.00,Above Avg
2,Mid,3,316,104,3,3.0,3.5,8.0,1,0.72,3 - 1,72.0,India,9.00,Above Avg
3,High,4,322,110,3,3.5,2.5,8.7,1,0.80,3 - 1,80.0,India,12.25,Above Avg
4,Mid,5,314,103,2,2.0,3.0,8.2,0,0.65,2 - 0,65.0,India,4.00,Avg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,High,396,324,110,3,3.5,3.5,9.0,1,0.82,3 - 1,82.0,India,12.25,Above Avg
396,High,397,325,107,3,3.0,3.5,9.1,1,0.84,3 - 1,84.0,India,9.00,Above Avg
397,High,398,330,116,4,5.0,4.5,9.4,1,0.91,4 - 1,91.0,India,25.00,Above Avg
398,Mid,399,312,103,3,3.5,4.0,8.8,0,0.67,3 - 0,67.0,India,12.25,Avg
399,High,400,333,117,4,5.0,4.0,9.5,1,0.95,4 - 1,95.0,India,25.00,Above Avg

In [101]:
#51 Standardize column names to snake_case (lowercase, replace spaces with _).

df1=df

df1=df1.columns.str.lower().str.replace(r'[^a-z0-9]','_',regex=True).str.replace(r'[_+]','_',regex=True).str.strip('_')

In [102]:
df1

Index(['admit_chance', 'serial_no', 'gre_score', 'toefl_score',
       'university_rating', 'sop', 'lor', 'cgpa', 'research',
       'chance_of_admit', 'rating_research', 'admit_probability', 'country',
       'ssop', 'gre_cat'],
      dtype='object')

In [104]:
#52 Create a new column showing difference between TOEFL Score and GRE Score/4.

df['new']=df['toefl score']-(df['gre score']/4)

In [106]:
#53 Find the average GRE Score for each University Rating.

df.groupby('university rating')['gre score'].mean().reset_index()

   university rating   gre score
0                  1  303.153846
1                  2  309.177570
2                  3  315.954887
3                  4  324.824324
4                 10  328.333333

In [110]:
#54 Count how many applicants have each University Rating.

df['university rating'].value_counts()

university rating
3     133
2     107
4      74
10     60
1      26
Name: count, dtype: int64

In [112]:
#55 Find the total number of students in each Research category.
df['research'].value_counts()

research
1    219
0    181
Name: count, dtype: int64

In [114]:
#56 Group by University Rating and show average TOEFL Score.

df.groupby('university rating')['toefl score'].mean().reset_index()

   university rating  toefl score
0                  1    99.076923
1                  2   103.523364
2                  3   106.887218
3                  4   111.824324
4                 10   113.666667

In [120]:
#57 Get the maximum Chance of Admit for each Research group.
df.groupby('research')['chance of admit '].max().reset_index()

   research  chance of admit
0         0              0.89
1         1              0.97

In [121]:
#58 Find minimum SOP value per University Rating.
df.groupby('university rating')['sop'].min().reset_index()

   university rating  sop
0                  1  2.0
1                  2  2.0
2                  3  2.0
3                  4  2.0
4                 10  3.0

In [128]:
#59 Count number of students with GRE Score ≥ 320 for each University Rating.

df[df['gre score']>=320].groupby('university rating').size().reset_index()

   university rating   0
0                  2  11
1                  3  49
2                  4  59
3                 10  56

In [130]:
#60 Calculate median CGPA grouped by Research.

df.groupby('research')['cgpa'].median().reset_index()

   research  cgpa
0         0   8.3
1         1   9.0

In [133]:
#61 Get the number of students per combination of University Rating and Research.

df.groupby(['university rating','research']).size().reset_index()

   university rating  research   0
0                  1         0  21
1                  1         1   5
2                  2         0  75
3                  2         1  32
4                  3         0  62
5                  3         1  71
6                  4         0  15
7                  4         1  59
8                 10         0   8
9                 10         1  52

In [142]:
#62 Find the mean GRE Score grouped by both Research and SOP.

df.groupby(['research','sop'])['gre score'].mean()
df.pivot_table(
    index='sop',
    columns='research',
    values='gre score',
    aggfunc='mean'
)

research           0           1
sop
2.0       308.481481  309.166667
2.5       307.696970  315.571429
3.0       311.352941  316.800000
3.4       301.409091  309.500000
3.5       310.925926  319.023256
4.0       311.476190  325.653061
4.5       320.833333  328.000000
5.0       306.400000  330.218750

In [146]:
#63 For each University Rating, find both min and max TOEFL Score.
df.groupby('university rating')['toefl score'].agg(['min','max'])

                   min  max
university rating
1                   92  109
2                   95  118
3                   97  120
4                  100  120
10                 103  120

In [148]:
#64 Display number of unique GRE Score values per University Rating.

df.groupby('university rating')['gre score'].unique().reset_index()

   university rating                                          gre score
0                  1  [302, 295, 300, 304, 294, 318, 297, 315, 298, ...
1                  2  [314, 308, 298, 310, 300, 299, 307, 316, 313, ...
2                  3  [316, 322, 321, 323, 325, 307, 311, 314, 317, ...
3                  4  [337, 324, 327, 328, 325, 338, 332, 334, 314, ...
4                 10  [330, 328, 334, 336, 340, 322, 331, 320, 326, ...

In [151]:
#65 Find the average of all numeric columns grouped by Research.

df.groupby('research').mean(numeric_only=True)

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,chance of admit,admit_probability,ssop,new
research,,,,,,,,,,,
0,208.519337,309.491713,104.143646,2.745856,3.153591,3.057459,8.255801,0.637680,63.767956,10.548729,26.770718
1,193.872146,322.853881,110.109589,4.739726,3.842922,3.763014,8.857534,0.795982,79.598174,15.382374,29.396119

In [154]:
#66 Get the count of applicants having CGPA>9 grouped by Research.

df[df['cgpa']>9].groupby('research').size()

research
0     6
1    96
dtype: int64

In [156]:
#67 For each SOP rating, find mean Chance of Admit.
df.groupby('sop')['chance of admit '].mean().reset_index()

   sop  chance of admit
0  2.0          0.602727
1  2.5          0.651277
2  3.0          0.683594
3  3.4          0.525385
4  3.5          0.713571
5  4.0          0.778000
6  4.5          0.843962
7  5.0          0.883514

In [158]:
#68 Calculate mean and std deviation of GRE Score per University Rating.

df.groupby('university rating')['gre score'].agg(['mean','std'])

                         mean       std
university rating
1                  303.153846  7.918042
2                  309.177570  8.503954
3                  315.954887  7.748768
4                  324.824324  9.917962
10                 328.333333  8.524475

In [46]:
#69 Get total number of students whose Chance of Admit > 0.8 per Research.\

df[df['chance of admit ']>0.8].shape[0]

117

In [49]:
df

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,admit_probability,GRE_Level,normalize gpa,Weighted_score
0,1,337,120,4,4.5,4.5,9.6,yes,0.92,2.855932,92.0,High,0.903226,129.90
1,2,324,109,4,4.0,4.5,8.9,yes,0.76,3.028037,76.0,High,0.677419,123.45
2,3,316,106,3,3.0,3.5,8.0,yes,0.72,3.038462,72.0,Low,0.387097,120.00
3,4,322,112,3,3.5,2.5,8.7,yes,0.80,2.927273,80.0,High,0.612903,123.35
4,5,314,105,2,2.0,3.0,8.2,no,0.65,3.048544,65.0,Low,0.451613,119.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,yes,0.82,2.945455,82.0,High,0.709677,124.10
396,397,325,109,3,3.0,3.5,9.1,yes,0.84,3.037383,84.0,High,0.741935,123.85
397,398,330,118,4,5.0,4.5,9.4,yes,0.91,2.844828,91.0,High,0.838710,127.30
398,399,312,105,3,3.5,4.0,8.8,no,0.67,3.029126,67.0,Low,0.645161,119.00
399,400,333,119,4,5.0,4.0,9.7,yes,0.95,2.846154,95.0,High,0.935484,128.55

In [69]:
#70 Find number of records for each distinct combination of University Rating, SOP, and LOR.

df.groupby(['University Rating','SOP','LOR ']).size().reset_index()

     University Rating  SOP  LOR    0
0                    1  1.0   1.0   1
1                    1  1.0   1.5   1
2                    1  1.0   2.0   1
3                    1  1.0   2.5   2
4                    1  1.5   1.5   1
..                 ...  ...   ...  ..
119                  5  4.5   5.0   3
120                  5  5.0   3.5   1
121                  5  5.0   4.0   3
122                  5  5.0   4.5   7
123                  5  5.0   5.0  13

[124 rows x 4 columns]

In [71]:
#71 Get the highest GRE Score among students with Research = 0.

df[df['Research']==0]['GRE Score'].agg('max')

339

In [76]:
#72 Find how many students in each Research category have CGPA > 9.

df[df['CGPA']>9].groupby('Research').size().reset_index()

   Research    0
0         0    9
1         1  104

In [77]:
#73 Calculate total GRE Score for each University Rating.

df.groupby('University Rating')['GRE Score'].sum().reset_index()

   University Rating  GRE Score
0                  1       7882
1                  2      33082
2                  3      42022
3                  4      24037
4                  5      19700

In [78]:
#74 Find mean Chance of Admit for each unique LOR score.

df.groupby('LOR ')['Chance of Admit '].mean().reset_index()

   LOR   Chance of Admit
0   1.0          0.420000
1   1.5          0.567143
2   2.0          0.563158
3   2.5          0.632564
4   3.0          0.674235
5   3.5          0.721096
6   4.0          0.776364
7   4.5          0.858444
8   5.0          0.883429

In [83]:
#75 Get number of students with same TOEFL Score grouped by that score.

df.groupby('TOEFL Score').size()

TOEFL Score
92      1
93      2
94      1
95      2
96      4
97      6
98      9
99     18
100    19
101    11
102    17
103    16
104    25
105    28
106    24
107    26
108    17
109    17
110    37
111    17
112    21
113    14
114    15
115     9
116    11
117     7
118     9
119     9
120     8
dtype: int64

In [102]:
#76  Find the group with the maximum average Chance of Admit.

ur=df.groupby('University Rating')['Chance of Admit '].mean().max()
gre=df.groupby('GRE Score')['Chance of Admit '].mean().max()
toefl=df.groupby('TOEFL Score')['Chance of Admit '].mean().max()
sop=df.groupby('SOP')['Chance of Admit '].mean().max()
lor=df.groupby('LOR ')['Chance of Admit '].mean().max()
cgpa=df.groupby('CGPA')['Chance of Admit '].mean().max()

a={'ur':ur,'gre':gre,'toefl':toefl,'sop':sop,'lor':lor,'cgpa':cgpa}
b=max(a,key=a.get)
b,a[b]

('cgpa', 0.97)

In [109]:
#77 Sort dataset by GRE Score in descending order.

dff=df.sort_values(by='GRE Score',ascending=False).reset_index()
dff

,index,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,202,203,340,120,5,4.5,4.5,9.91,1,0.97
1,33,34,340,114,5,4.0,4.0,9.60,1,0.90
2,84,85,340,115,5,4.5,4.5,9.45,1,0.94
3,143,144,340,120,4,4.5,4.0,9.92,1,0.97
4,81,82,340,120,4,5.0,5.0,9.50,1,0.96
...,...,...,...,...,...,...,...,...,...,...
395,79,80,294,93,1,1.5,2.0,7.36,0,0.46
396,272,273,294,95,1,1.5,1.5,7.64,0,0.49
397,168,169,293,97,2,2.0,4.0,7.80,1,0.64
398,377,378,290,100,1,1.5,2.0,7.56,0,0.47
399,117,118,290,104,4,2.0,2.5,7.46,0,0.45

In [111]:
#78 Sort by University Rating, then CGPA.

dff=df.sort_values(by=['University Rating', 'CGPA'], ascending=False)
dff

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
202,203,340,120,5,4.5,4.5,9.91,1,0.97
203,204,334,120,5,4.0,5.0,9.87,1,0.97
385,386,335,117,5,5.0,5.0,9.82,1,0.96
24,25,336,119,5,4.0,3.5,9.80,1,0.97
34,35,331,112,5,4.0,5.0,9.80,1,0.94
...,...,...,...,...,...,...,...,...,...
79,80,294,93,1,1.5,2.0,7.36,0,0.46
347,348,299,94,1,1.0,1.0,7.34,0,0.42
348,349,302,99,1,2.0,2.0,7.25,0,0.57
28,29,295,93,1,2.0,2.0,7.20,0,0.46
58,59,300,99,1,3.0,2.0,6.80,1,0.36

In [115]:
#79 Display top 5 rows with highest Chance of Admit.

df.sort_values(by='Chance of Admit ', ascending=False).head(5)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
143,144,340,120,4,4.5,4.0,9.92,1,0.97
24,25,336,119,5,4.0,3.5,9.80,1,0.97
202,203,340,120,5,4.5,4.5,9.91,1,0.97
203,204,334,120,5,4.0,5.0,9.87,1,0.97
71,72,336,112,5,5.0,5.0,9.76,1,0.96

In [116]:
#80 Sort values by TOEFL Score ascending.

df.sort_values(by='TOEFL Score',ascending=True)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
368,369,298,92,1,2.0,2.0,7.88,0,0.51
79,80,294,93,1,1.5,2.0,7.36,0,0.46
28,29,295,93,1,2.0,2.0,7.20,0,0.46
347,348,299,94,1,1.0,1.0,7.34,0,0.42
272,273,294,95,1,1.5,1.5,7.64,0,0.49
...,...,...,...,...,...,...,...,...,...
203,204,334,120,5,4.0,5.0,9.87,1,0.97
202,203,340,120,5,4.5,4.5,9.91,1,0.97
143,144,340,120,4,4.5,4.0,9.92,1,0.97
81,82,340,120,4,5.0,5.0,9.50,1,0.96
297,298,320,120,3,4.0,4.5,9.11,0,0.86

In [117]:
#Set Serial No. as index.

df.set_index('Serial No.')

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...
396,324,110,3,3.5,3.5,9.04,1,0.82
397,325,107,3,3.0,3.5,9.11,1,0.84
398,330,116,4,5.0,4.5,9.45,1,0.91
399,312,103,3,3.5,4.0,8.78,0,0.67
400,333,117,4,5.0,4.0,9.66,1,0.95

In [120]:
#81 Reset index to default.

df.reset_index(drop=True)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [121]:
#82 Sort dataset by multiple columns: Research and Chance of Admit.

df.sort_values(['Research','Chance of Admit '])

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
92,93,298,98,2,4.0,3.0,8.03,0,0.34
376,377,297,96,2,2.5,2.0,7.43,0,0.34
94,95,303,99,3,2.0,2.5,7.66,0,0.36
91,92,299,97,3,5.0,3.5,7.66,0,0.38
375,376,304,101,2,2.0,2.5,7.66,0,0.38
...,...,...,...,...,...,...,...,...,...
385,386,335,117,5,5.0,5.0,9.82,1,0.96
24,25,336,119,5,4.0,3.5,9.80,1,0.97
143,144,340,120,4,4.5,4.0,9.92,1,0.97
202,203,340,120,5,4.5,4.5,9.91,1,0.97
203,204,334,120,5,4.0,5.0,9.87,1,0.97

In [122]:
#83 Sort all applicants by CGPA then GRE Score descending.

df.sort_values(['CGPA','GRE Score'],ascending=[True,False])

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
58,59,300,99,1,3.0,2.0,6.80,1,0.36
28,29,295,93,1,2.0,2.0,7.20,0,0.46
348,349,302,99,1,2.0,2.0,7.25,0,0.57
118,119,296,99,2,3.0,3.5,7.28,0,0.47
29,30,310,99,2,1.5,2.0,7.30,0,0.54
...,...,...,...,...,...,...,...,...,...
34,35,331,112,5,4.0,5.0,9.80,1,0.94
385,386,335,117,5,5.0,5.0,9.82,1,0.96
203,204,334,120,5,4.0,5.0,9.87,1,0.97
202,203,340,120,5,4.5,4.5,9.91,1,0.97
143,144,340,120,4,4.5,4.0,9.92,1,0.97

In [124]:
#84 Retrieve bottom 10 rows after sorting by GRE Score.

df.sort_values(by='GRE Score',ascending=True).tail(10)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
47,48,339,119,5,4.5,4.0,9.70,0,0.89
130,131,339,114,5,4.0,4.5,9.76,1,0.96
81,82,340,120,4,5.0,5.0,9.50,1,0.96
33,34,340,114,5,4.0,4.0,9.60,1,0.90
84,85,340,115,5,4.5,4.5,9.45,1,0.94
25,26,340,120,5,4.5,4.5,9.60,1,0.94
202,203,340,120,5,4.5,4.5,9.91,1,0.97
384,385,340,113,4,5.0,5.0,9.74,1,0.96
143,144,340,120,4,4.5,4.0,9.92,1,0.97
284,285,340,112,4,5.0,4.5,9.66,1,0.94

In [126]:
#85 Use .nlargest() to get top 5 CGPA values.
df['CGPA'].nlargest(5).reset_index()

   index  CGPA
0    143  9.92
1    202  9.91
2    203  9.87
3    385  9.82
4     24  9.80

In [127]:
#86 Use .nsmallest() to get lowest 5 TOEFL Score values.

df['TOEFL Score'].nsmallest(5).reset_index()

   index  TOEFL Score
0    368           92
1     28           93
2     79           93
3    347           94
4     78           95

In [135]:
#87 Add a new DataFrame containing only students with Research = 1 and merge it with main dataset.
a=df[df['Research']==1]
dff=pd.concat([df,a],ignore_index=True)
dff

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
614,395,329,111,4,4.5,4.0,9.23,1,0.89
615,396,324,110,3,3.5,3.5,9.04,1,0.82
616,397,325,107,3,3.0,3.5,9.11,1,0.84
617,398,330,116,4,5.0,4.5,9.45,1,0.91
618,400,333,117,4,5.0,4.0,9.66,1,0.95

In [138]:
#88 Create two DataFrames — one for Research = 0, another for Research = 1 — and concatenate them.

a=df[df['Research']==1]
b=df[df['Research']==0]

pd.concat([a,b],ignore_index=False)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
5,6,330,115,5,4.5,3.0,9.34,1,0.90
...,...,...,...,...,...,...,...,...,...
388,389,296,97,2,1.5,2.0,7.80,0,0.49
390,391,314,102,2,2.0,2.5,8.24,0,0.64
391,392,318,106,3,2.0,3.0,8.65,0,0.71
393,394,317,104,2,3.0,3.0,8.76,0,0.77
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [143]:
#89 Merge two datasets on University Rating.

df1=df[['GRE Score','TOEFL Score','University Rating']]
df2=df[['SOP','LOR ','University Rating']]

pd.merge(df1,df2,on='University Rating',how='right')

       GRE Score  TOEFL Score  University Rating  SOP  LOR
0            337          118                  4  4.5   4.5
1            324          107                  4  4.5   4.5
2            327          111                  4  4.5   4.5
3            328          112                  4  4.5   4.5
4            325          114                  4  4.5   4.5
...          ...          ...                ...  ...   ...
38885        340          113                  4  5.0   4.0
38886        326          112                  4  5.0   4.0
38887        329          111                  4  5.0   4.0
38888        330          116                  4  5.0   4.0
38889        333          117                  4  5.0   4.0

[38890 rows x 5 columns]

In [146]:
#90 Join two DataFrames with same index using .join().

df1=df[['GRE Score','TOEFL Score','University Rating']]
df2=df[['SOP','LOR ','CGPA']]

df1.join(df2)

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA
0          337          118                  4  4.5   4.5  9.65
1          324          107                  4  4.0   4.5  8.87
2          316          104                  3  3.0   3.5  8.00
3          322          110                  3  3.5   2.5  8.67
4          314          103                  2  2.0   3.0  8.21
..         ...          ...                ...  ...   ...   ...
395        324          110                  3  3.5   3.5  9.04
396        325          107                  3  3.0   3.5  9.11
397        330          116                  4  5.0   4.5  9.45
398        312          103                  3  3.5   4.0  8.78
399        333          117                  4  5.0   4.0  9.66

[400 rows x 6 columns]

In [149]:
#91 Use .loc[] to select students with index from 10 to 20.

df.loc[10:20]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
10,11,325,106,3,3.5,4.0,8.4,1,0.52
11,12,327,111,4,4.0,4.5,9.0,1,0.84
12,13,328,112,4,4.0,4.5,9.1,1,0.78
13,14,307,109,3,4.0,3.0,8.0,1,0.62
14,15,311,104,3,3.5,2.0,8.2,1,0.61
15,16,314,105,3,3.5,2.5,8.3,0,0.54
16,17,317,107,3,4.0,3.0,8.7,0,0.66
17,18,319,106,3,4.0,3.0,8.0,1,0.65
18,19,318,110,3,4.0,3.0,8.8,0,0.63
19,20,303,102,3,3.5,3.0,8.5,0,0.62
20,21,312,107,3,3.0,2.0,7.9,1,0.64

In [155]:
#92 Use .iloc[] to select the first 5 rows and first 3 columns.

df.iloc[0:5,0:3]

   Serial No.  GRE Score  TOEFL Score
0           1        337          118
1           2        324          107
2           3        316          104
3           4        322          110
4           5        314          103

In [160]:
#93 Display all columns except Serial No..

df.iloc[:,1:]

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...
395,324,110,3,3.5,3.5,9.04,1,0.82
396,325,107,3,3.0,3.5,9.11,1,0.84
397,330,116,4,5.0,4.5,9.45,1,0.91
398,312,103,3,3.5,4.0,8.78,0,0.67
399,333,117,4,5.0,4.0,9.66,1,0.95

In [161]:
#94 Select only GRE Score, TOEFL Score, and CGPA columns.

df[['GRE Score','TOEFL Score','CGPA']]

     GRE Score  TOEFL Score  CGPA
0          337          118  9.65
1          324          107  8.87
2          316          104  8.00
3          322          110  8.67
4          314          103  8.21
..         ...          ...   ...
395        324          110  9.04
396        325          107  9.11
397        330          116  9.45
398        312          103  8.78
399        333          117  9.66

[400 rows x 3 columns]

In [163]:
#95 Sort all rows in reverse alphabetical order of index.

df.sort_index(ascending=False)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
399,400,333,117,4,5.0,4.0,9.66,1,0.95
398,399,312,103,3,3.5,4.0,8.78,0,0.67
397,398,330,116,4,5.0,4.5,9.45,1,0.91
396,397,325,107,3,3.0,3.5,9.11,1,0.84
395,396,324,110,3,3.5,3.5,9.04,1,0.82
...,...,...,...,...,...,...,...,...,...
4,5,314,103,2,2.0,3.0,8.21,0,0.65
3,4,322,110,3,3.5,2.5,8.67,1,0.80
2,3,316,104,3,3.0,3.5,8.00,1,0.72
1,2,324,107,4,4.0,4.5,8.87,1,0.76
0,1,337,118,4,4.5,4.5,9.65,1,0.92

In [167]:
#95 Extract rows with even index numbers only.

#df.iloc[::2]
df[df.index%2==0]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
2,3,316,104,3,3.0,3.5,8.00,1,0.72
4,5,314,103,2,2.0,3.0,8.21,0,0.65
6,7,321,109,3,3.0,4.0,8.20,1,0.75
8,9,302,102,1,2.0,1.5,8.00,0,0.50
...,...,...,...,...,...,...,...,...,...
390,391,314,102,2,2.0,2.5,8.24,0,0.64
392,393,326,112,4,4.0,3.5,9.12,1,0.84
394,395,329,111,4,4.5,4.0,9.23,1,0.89
396,397,325,107,3,3.0,3.5,9.11,1,0.84
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [173]:
#96 Display first and last 3 rows of dataset together.

a=df.iloc[0:3] 
b=df.tail(3)

pd.concat([a,b])

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [174]:
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [179]:
#97 Combine two DataFrames vertically using pd.concat().

pd.concat([df1,df2],axis=0)

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA
0        337.0        118.0                4.0  NaN   NaN   NaN
1        324.0        107.0                4.0  NaN   NaN   NaN
2        316.0        104.0                3.0  NaN   NaN   NaN
3        322.0        110.0                3.0  NaN   NaN   NaN
4        314.0        103.0                2.0  NaN   NaN   NaN
..         ...          ...                ...  ...   ...   ...
395        NaN          NaN                NaN  3.5   3.5  9.04
396        NaN          NaN                NaN  3.0   3.5  9.11
397        NaN          NaN                NaN  5.0   4.5  9.45
398        NaN          NaN                NaN  3.5   4.0  8.78
399        NaN          NaN                NaN  5.0   4.0  9.66

[800 rows x 6 columns]

In [192]:
#98 Sort dataset based on the rounded value of Chance of Admit.

df.sort_values(by='Chance of Admit ', key=lambda x: x.round(), inplace=False)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
60,61,309,100,2,3.0,3.0,8.10,0,0.48
28,29,295,93,1,2.0,2.0,7.20,0,0.46
96,97,306,100,2,3.0,3.0,8.00,0,0.48
94,95,303,99,3,2.0,2.5,7.66,0,0.36
93,94,301,97,2,3.0,3.0,7.88,1,0.44
...,...,...,...,...,...,...,...,...,...
144,145,325,112,2,3.0,3.5,8.96,1,0.80
143,144,340,120,4,4.5,4.0,9.92,1,0.97
142,143,331,115,5,4.0,3.5,9.44,1,0.92
151,152,332,116,5,5.0,5.0,9.28,1,0.94
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [197]:
#100 Rearrange columns alphabetically.

df.columns=df.columns.sort_values()

In [196]:
df

,CGPA,Chance of Admit,GRE Score,LOR,Research,SOP,Serial No.,TOEFL Score,University Rating
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [199]:
df.to_csv('Admission_Predic_Completed.csv', index=False)