In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Airbnb_Open_Data (1).csv')

C:\Users\AKASH\AppData\Local\Temp\ipykernel_32300\1396479858.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('Airbnb_Open_Data (1).csv')

In [3]:
df.head(10)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$14,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN

In [4]:
#2. Show the last 5 rows of the dataset.

df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [5]:
#3. Get all column names in the dataset.

df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [6]:
#4. Display the shape (rows, columns) of the dataset.

df.shape

(102599, 26)

In [7]:
#5. Check the data type of each column.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [8]:
#6. Display only the columns: name, price, and room_type.

df[['NAME','price','room type']]

,NAME,price,room type
0,Clean & quiet apt home by the park,$966,Private room
1,Skylit Midtown Castle,$142,Entire home/apt
2,THE VILLAGE OF HARLEM....NEW YORK !,$620,Private room
3,NaN,$368,Entire home/apt
4,Entire Apt: Spacious Studio/Loft by central park,$204,Entire home/apt
...,...,...,...
102594,Spare room in Williamsburg,$844,Private room
102595,Best Location near Columbia U,$837,Private room
102596,"Comfy, bright room in Brooklyn",$988,Private room
102597,Big Studio-One Stop from Midtown,$546,Entire home/apt
102598,585 sf Luxury Studio,"$1,032",Entire home/apt

In [9]:
#7 Retrieve all unique values in the room_type column.

df['room type'].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'],
      dtype=object)

In [10]:
# 8. Count how many unique host IDs exist in the dataset.

df['host id'].unique()

array([80014485718, 52335172823, 78829239556, ..., 23801060917,
       15593031571, 93578954226], dtype=int64)

In [11]:
df['price'].isna().sum()

247

In [12]:
import re
df['price']=df['price'].replace(r'[$,]','',regex=True)

In [13]:
df['price']=pd.to_numeric(df['price'])

In [14]:
#9 9. Select all rows where price is greater than 100.

df[df['price']>100]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [15]:
#10. Select all listings where room_type is “Entire home/apt”.

df[df['room type']=='Entire home/apt']

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,$64,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102590,6090228,Wonderful artists' loft in Brooklyn,9184535139,unconfirmed,Daniel,Brooklyn,Crown Heights,40.66673,-73.96127,United States,...,$50,1.0,0.0,NaN,NaN,1.0,1.0,276.0,#NAME?,NaN
102591,6090781,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,...,$228,5.0,17.0,1/4/2019,0.35,5.0,1.0,134.0,#NAME?,NaN
102592,6091333,3BR/1 Ba in TriBeCa w/ outdoor deck,53266862889,unconfirmed,Nick,Manhattan,Tribeca,40.71845,-74.01183,United States,...,$157,1.0,0.0,NaN,NaN,2.0,1.0,177.0,Guests should treat my home as if it were thei...,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [16]:
#11. Show all listings in the city “New York”.

a = df[df['neighbourhood'].str.contains('york', case=False, na=False)]
a

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
522,1289637,Family & Friends in New York City,9750353852,unconfirmed,Emma,Brooklyn,East New York,40.67497,-73.87305,United States,...,$236,3.0,177.0,6/29/2019,1.86,2.0,1.0,145.0,Overall please treat the apartment as you woul...,NaN
854,1473000,Feel like you never leave your home,54872866190,verified,Dixon,Brooklyn,East New York,40.66795,-73.89232,United States,...,$37,1.0,119.0,6/30/2019,1.39,1.0,2.0,25.0,"In order to provide a healthy, comfortable and...",NaN
1042,1576833,1 Bedroom Apt - Close to JFK & City,14445647831,unconfirmed,Terrance,Brooklyn,East New York,40.65408,-73.87883,United States,...,$159,4.0,40.0,6/17/2019,0.46,3.0,1.0,287.0,No Smoking No Pets,NaN
1517,1839175,Cozy Private Bedroom $800 Month,62089478705,unconfirmed,Maria Daniela,Brooklyn,East New York,40.67635,-73.89124,United States,...,$89,3.0,13.0,5/29/2019,0.16,5.0,1.0,400.0,NaN,NaN
2930,2619575,ON A BUDGET COZY IN BROOKLYN In NYC,47384441503,unconfirmed,Majar,Brooklyn,East New York,40.66759,-73.88584,United States,...,$20,3.0,52.0,5/27/2019,0.74,3.0,8.0,244.0,- - NO PETS! NO SMOKING ON PREMISES! NO PART...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102051,57364103,"A cozy getaway, home away from home",55697801194,verified,Isaiah,Brooklyn,East New York,40.66130,-73.89088,United States,...,NaN,1.0,0.0,NaN,NaN,4.0,1.0,88.0,NaN,NaN
102286,20307535,"Comfy, Beautiful Apt with Breakfast Included",83382332065,verified,Deborah/Aston,Brooklyn,East New York,40.67661,-73.87488,United States,...,$177,2.0,43.0,7/5/2019,4.13,2.0,1.0,95.0,"This apartment is located on a third floor, no...",NaN
102323,20327970,The luxury East New York,30396802642,verified,Corie,Brooklyn,East New York,40.66526,-73.89370,United States,...,$71,2.0,34.0,6/4/2019,3.59,3.0,2.0,273.0,NaN,NaN
102441,20393141,Large bedroom ensuite,48039848434,verified,Samantha,Brooklyn,East New York,40.67154,-73.87913,United States,...,$201,3.0,2.0,10/7/2018,0.19,5.0,1.0,179.0,"If you are new to Airbnb, the idea is that I’m...",NaN
102554,6070345,Beautiful Private Room,47602000155,verified,Christina,Brooklyn,East New York,40.67240,-73.88118,United States,...,$107,20.0,29.0,3/30/2019,0.59,4.0,3.0,309.0,No pets. No smoking. Please :),NaN

In [17]:
#12. Retrieve only the host_name and neighbourhood columns.

df[['host name','neighbourhood']]

          host name        neighbourhood
0          Madaline           Kensington
1             Jenna              Midtown
2             Elise               Harlem
3             Garry         Clinton Hill
4            Lyndon          East Harlem
...             ...                  ...
102594         Krik         Williamsburg
102595        Mifan  Morningside Heights
102596        Megan           Park Slope
102597  Christopher     Long Island City
102598      Rebecca      Upper West Side

[102599 rows x 2 columns]

In [18]:
#13 13. Display all listings with more than 2 bedrooms.
df['room type'].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'],
      dtype=object)

In [19]:
# 14. Retrieve all listings that have a minimum_nights less than 3.

df[df['minimum nights']<3]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,$64,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN
12,1007964,Central Manhattan/near Broadway,88136055909,verified,NaN,Manhattan,Hell's Kitchen,40.76076,-73.98867,United States,...,$143,2.0,188.0,6/23/2019,1.50,4.0,1.0,258.0,- One of the bedroom closets is not accessible...,NaN
14,1009068,Wonderful Guest Bedroom in Manhattan for SINGLES,88920244552,verified,Leonardo,Manhattan,Upper West Side,40.79826,-73.96113,United States,...,$30,2.0,113.0,7/5/2019,0.91,3.0,1.0,68.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,$220,1.0,8.0,9/6/2015,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...,NaN
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [20]:
#15 Show listings where availability_365 is zero.

df[df['availability 365']==0]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
154,1086390,NaN,47292670441,unconfirmed,Dainton,Brooklyn,Prospect Heights,40.67410,-73.96595,United States,...,$162,15.0,4.0,8/27/2018,0.05,3.0,1.0,0.0,Events or parties are a separate charge at our...,NaN
243,1135545,Huge Chelsea Loft,27743402115,verified,Thomas,Manhattan,Chelsea,40.74358,-74.00027,United States,...,$119,2.0,35.0,7/27/2017,0.34,1.0,1.0,0.0,- has to be clean!,NaN
862,1477419,Your Own 2 Br Apt Bedford and Grand,98053399694,unconfirmed,Montgomery,Brooklyn,Williamsburg,40.71532,-73.96064,United States,...,$97,3.0,236.0,6/18/2019,2.74,NaN,2.0,0.0,No smoking allowed in the house. No pets. No...,NaN
1541,1852430,"LARGE PRIVATE FLOOR IN BROOKLYN, NY",55884191073,verified,Eric,Brooklyn,Bedford-Stuyvesant,40.69128,-73.93653,United States,...,$74,4.0,239.0,6/26/2019,2.89,1.0,2.0,0.0,NaN,NaN
2408,2331274,Central Park Room/Bath with a View!,84337043060,unconfirmed,William,Manhattan,Upper West Side,40.79631,-73.96152,United States,...,$34,3.0,118.0,1/23/2019,1.61,2.0,1.0,0.0,Please clean up before checking out. Any major...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102462,20404740,New York Apartment,98342871281,unconfirmed,Karen,Manhattan,Civic Center,40.71310,-74.00527,United States,...,$222,15.0,0.0,NaN,NaN,3.0,1.0,0.0,"NO SMOKING, please stop smoking a block away s...",NaN
102463,20405292,Affordable bedroom in Brooklyn townhouse.,78907850230,verified,Julie,Brooklyn,East Flatbush,40.65040,-73.95011,United States,...,$197,3.0,2.0,2/18/2019,0.19,3.0,2.0,0.0,NaN,NaN
102465,20406397,beautiful modern 1 bed room apt,7095669452,unconfirmed,Alex,Manhattan,Chelsea,40.74813,-74.00478,United States,...,$194,2.0,4.0,5/28/2019,0.45,2.0,1.0,0.0,NaN,NaN
102468,20408053,"Clean, Cozy Home in Perfect Park Slope Location",52339470834,unconfirmed,Young Jean,Brooklyn,Park Slope,40.68178,-73.97957,United States,...,$136,120.0,0.0,NaN,NaN,5.0,1.0,0.0,All guests are expected to be respectful and m...,NaN
102503,6042178,"Perfect for Cat, Book, Park Lovers!",17949645201,verified,Laura,Brooklyn,Flatbush,40.65371,-73.95623,United States,...,$80,2.0,12.0,12/19/2015,0.25,1.0,1.0,0.0,No smoking in the unit or in the building (str...,NaN

In [21]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [22]:
df['service fee']=df['service fee'].replace(r'[$,]','',regex=True)

In [23]:
df['service fee']=pd.to_numeric(df['service fee'])

In [24]:
df.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,193.0,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,28.0,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,124.0,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,74.0,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,41.0,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [25]:
#16. Display the top 10 most expensive listings.

df['a']=df['price']+df['service fee']

In [26]:
df.sort_values(by='a',ascending=False).head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
53366,30475378,Modern & Beauty 3 BR in Manhattan close to Wal...,10777689853,unconfirmed,Antonin,Manhattan,Financial District,40.70395,-74.00813,United States,...,3.0,10.0,2/18/2022,2.33,2.0,1.0,237.0,NaN,NaN,1440.0
54631,31174037,Luxury Duplex Unit w/Private Rooftop & Balcony,3229595936,verified,Esaie,Brooklyn,Crown Heights,40.67564,-73.93059,United States,...,2.0,1.0,2/13/2022,1.00,3.0,1.0,305.0,NaN,NaN,1440.0
9805,6416638,Private room in hip & historic area,40836583876,unconfirmed,Ilean,Brooklyn,Bedford-Stuyvesant,40.68346,-73.95551,United States,...,2.0,30.0,4/30/2019,1.97,1.0,1.0,287.0,NaN,NaN,1440.0
66682,37829805,"Feel-Good Decor, Lux Private Room Great Loc 4-4",90299456137,verified,Lydia,Brooklyn,Williamsburg,40.70932,-73.96436,United States,...,30.0,1.0,10/10/2020,0.06,3.0,2.0,0.0,NaN,NaN,1440.0
86099,48553814,Luxurious SOHO 2 BR Washington Sq Park,43120829353,verified,Corporate Housing,Manhattan,Greenwich Village,40.72807,-74.00041,United States,...,30.0,4.0,6/16/2019,0.14,2.0,91.0,182.0,NaN,NaN,1440.0

In [27]:
#17. Sort the dataset by price in descending order.

df.sort_values(by='price',ascending=False)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
64304,36516435,Great 1BD waterfront City Island NY,83460973881,verified,Alex,Bronx,City Island,40.85343,-73.78811,United States,...,30.0,108.0,8/25/2021,1.09,5.0,1.0,31.0,NaN,NaN,1440.0
70765,40084846,Beautiful Central Harlem sleeps 4,79723019119,verified,London,Manhattan,Harlem,40.80861,-73.94574,United States,...,3.0,123.0,7/2/2019,1.73,1.0,3.0,248.0,NaN,NaN,1440.0
23345,13894780,法拉盛中心公寓楼高层,35971606080,unconfirmed,Zheng,Queens,Flushing,40.75575,-73.83261,United States,...,2.0,45.0,5/6/2019,1.77,2.0,2.0,45.0,NaN,NaN,1440.0
38851,22458743,Private room (Paris Room) in Bushwick Brownstone,31603093641,verified,Rob,Brooklyn,Bushwick,40.68583,-73.90985,United States,...,1.0,10.0,5/6/2019,1.36,3.0,2.0,365.0,NO PETS. NO SMOKING. NO PARTIES. No recreat...,NaN,1440.0
102191,35580287,One cozy bedroom near Verrazano bridge and ferry,32202051101,unconfirmed,Chun Kit,Staten Island,Shore Acres,40.61126,-74.06789,United States,...,1.0,5.0,11/7/2021,0.59,5.0,1.0,0.0,NaN,NaN,1440.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102046,57361342,Sunny budget friendly room in Bushwick,29964876857,verified,NaN,Brooklyn,Bushwick,40.69370,-73.91006,United States,...,5.0,3.0,4/9/2018,0.11,1.0,1.0,0.0,Please be mindful that I live in the same buil...,NaN,NaN
102047,57361894,"Cozy Apartment on Bedford Ave, Brooklyn",92852058426,unconfirmed,NaN,Brooklyn,Williamsburg,40.71284,-73.96284,United States,...,7.0,15.0,1/1/2018,0.55,4.0,1.0,0.0,NaN,NaN,NaN
102048,57362446,Your 1 bedroom home away from home!,95572379802,verified,NaN,Manhattan,Upper West Side,40.79563,-73.97634,United States,...,3.0,38.0,6/10/2019,1.40,3.0,1.0,31.0,NaN,NaN,NaN
102049,57362999,MASTER Cozy Bedroom Queen size 2 blocks Timesq...,80154173698,verified,NaN,Manhattan,Hell's Kitchen,40.76125,-73.98945,United States,...,1.0,81.0,3/5/2019,2.96,2.0,2.0,0.0,- I work at home and prefer to rent to folks w...,NaN,NaN
102050,57363551,Sunny Brownstone Studio in BedStuy Brooklyn,11145329848,unconfirmed,Jamal,Brooklyn,Bedford-Stuyvesant,40.68221,-73.94618,United States,...,2.0,104.0,6/12/2019,3.69,5.0,1.0,268.0,NaN,NaN,NaN

In [28]:
#18. Sort listings first by city, then by price ascending.

df.sort_values(by='price')[['neighbourhood','price']]

             neighbourhood  price
24254   Bedford-Stuyvesant   50.0
61234             Canarsie   50.0
69032           St. Albans   50.0
45551             Flushing   50.0
60981    Greenwich Village   50.0
...                    ...    ...
102046            Bushwick    NaN
102047        Williamsburg    NaN
102048     Upper West Side    NaN
102049      Hell's Kitchen    NaN
102050  Bedford-Stuyvesant    NaN

[102599 rows x 2 columns]

In [29]:
#19 19. Check how many rows belong to each city.

df['neighbourhood'].value_counts()

neighbourhood
Bedford-Stuyvesant        7937
Williamsburg              7775
Harlem                    5466
Bushwick                  4982
Hell's Kitchen            3965
                          ...
Rossville                    3
Lighthouse Hill              3
Fort Wadsworth               2
Glen Oaks                    2
Chelsea, Staten Island       1
Name: count, Length: 224, dtype: int64

In [30]:
#20 20. Display only listings whose name contains the word “Cozy”.

df[df['NAME'].str.contains('cozy',case=False,na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,692.0
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN,349.0
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN,383.0
52,1030056,Cozy 1BD on Central Park West in New York City,50562514538,unconfirmed,Madaline,Manhattan,Upper West Side,40.78635,-73.97008,United States,...,NaN,73.0,7/7/2019,0.63,3.0,1.0,NaN,No smoking anywhere on the property. Quiet and...,NaN,1081.0
90,1051043,Cozy Bedroom in Williamsburg 3 BR,14067827221,unconfirmed,Lilianna,NaN,Williamsburg,40.71156,-73.96218,United States,...,3.0,174.0,6/22/2019,1.54,5.0,4.0,NaN,Dryer and Washing Machine are in Basement (1.0...,NaN,319.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102538,6061509,Cozy Bedroom in Renovated Harlem Apartment,75674201040,unconfirmed,Delesia,Manhattan,Harlem,40.81435,-73.94588,United States,...,2.0,1.0,7/20/2016,0.03,3.0,1.0,106.0,NaN,NaN,388.0
102543,6064270,Nice and Cozy Room,6402191466,verified,Melissa,Manhattan,East Village,40.72294,-73.98570,United States,...,1.0,0.0,NaN,NaN,4.0,1.0,237.0,NaN,NaN,325.0
102547,6066479,"Safe,quiet,cozy,Washington Hts Apt",92398842230,verified,Lynn,Manhattan,Washington Heights,40.84454,-73.94188,United States,...,1.0,0.0,NaN,NaN,4.0,1.0,44.0,NaN,NaN,494.0
102553,6069793,"Custom Designed Cozy Garden Apt,",7756381071,unconfirmed,Jean& Toney,Brooklyn,Canarsie,40.64574,-73.90781,United States,...,7.0,0.0,NaN,NaN,4.0,3.0,95.0,"- Absolutely no smoking in, on or near the pro...",NaN,244.0
102564,6075868,Clean & Cozy- Private Room by Park and Subway!,33983881137,verified,Jayanthi,Brooklyn,Flatbush,40.65452,-73.95960,United States,...,2.0,55.0,6/14/2018,1.12,5.0,1.0,192.0,NaN,NaN,726.0

In [31]:
#21. Display all listings where price is between 100 and 200.

df[(df['price']>100)&(df['price']<200)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,170.0
14,1009068,Wonderful Guest Bedroom in Manhattan for SINGLES,88920244552,verified,Leonardo,Manhattan,Upper West Side,40.79826,-73.96113,United States,...,2.0,113.0,7/5/2019,0.91,3.0,1.0,68.0,NaN,NaN,179.0
22,1013487,CBG CtyBGd HelpsHaiti rm#1:1-4,53754237010,verified,Mary,Brooklyn,Park Slope,40.68069,-73.97706,United States,...,2.0,130.0,7/1/2019,1.09,4.0,6.0,54.0,Arrival time can be no later than 10:00PM. No ...,NaN,160.0
35,1020667,Large B&B Style rooms,57938703679,unconfirmed,Jared,Brooklyn,Bedford-Stuyvesant,40.68310,-73.95473,United States,...,1.0,74.0,5/12/2019,0.66,NaN,2.0,76.0,"No smoking, this is non-negotiable. No illega...",NaN,229.0
77,1043863,Manhattan Room,11468499446,verified,Sofia,NaN,Upper East Side,40.76865,-73.95058,United States,...,1.0,142.0,7/6/2019,1.50,4.0,1.0,NaN,I'm a semi kosher vegetarian which means that ...,NaN,139.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102500,6040521,*TERRA GARDEN* 1 Bedroom Garden Apartment,67984530373,verified,Juliana,Manhattan,Upper West Side,40.78180,-73.98483,United States,...,30.0,7.0,10/31/2018,0.19,3.0,34.0,22.0,"No smoking please, no pets to protect our hard...",NaN,235.0
102534,6059299,Upper East Side - 1 Bedroom Queen,28301379386,verified,Dani,Manhattan,Upper East Side,40.77734,-73.95779,United States,...,7.0,0.0,NaN,NaN,4.0,1.0,188.0,Please Note: This unit was just renovated in M...,NaN,181.0
102546,6065927,LG Bright Apartment,10408461200,verified,Katie,Manhattan,Morningside Heights,40.80481,-73.96375,United States,...,21.0,4.0,1/6/2018,0.09,4.0,1.0,313.0,#NAME?,NaN,155.0
102563,6075316,Large 1Br Apt + Balcony in LES!,59240106692,unconfirmed,Elena,Manhattan,Lower East Side,40.72115,-73.98308,United States,...,5.0,1.0,9/16/2015,0.02,2.0,1.0,133.0,NaN,NaN,194.0
102578,6083601,Sunny & Spacious near Central Park,41624631525,verified,Guida,Manhattan,East Harlem,40.79674,-73.94449,United States,...,5.0,4.0,1/6/2016,0.08,1.0,1.0,323.0,NaN,NaN,212.0

In [32]:
#22. Show all listings that are either in “Los Angeles” or “San Francisco”.

df[df['neighbourhood group'].str.contains('Francisco',case=False,na=False)]

Empty DataFrame
Columns: [id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, last review, reviews per month, review rate number, calculated host listings count, availability 365, house_rules, license, a]
Index: []

[0 rows x 27 columns]

In [33]:
#23. Retrieve listings whose number_of_reviews is greater than 50.

df[df['number of reviews']>50]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,442.0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,692.0
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN,1222.0
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN,349.0
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN,383.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102579,6084153,Alexander's 2BR Luxury Quarters,32736284559,verified,Juan,Brooklyn,Bedford-Stuyvesant,40.68740,-73.93830,United States,...,3.0,123.0,6/26/2019,2.53,4.0,1.0,203.0,NaN,NaN,353.0
102580,6084705,"Near LGA, Citifield, US Open Tennis",97606085736,verified,Carmen,Queens,East Elmhurst,40.76578,-73.86424,United States,...,1.0,209.0,6/11/2019,4.38,3.0,1.0,270.0,House Rules 1. Check-in is 4 pm local time. If...,NaN,731.0
102584,6086914,2 block walk from the beach in NYC,70051719594,verified,Vladimir,Queens,Arverne,40.59270,-73.78990,United States,...,2.0,89.0,5/26/2019,1.82,2.0,1.0,394.0,NaN,NaN,679.0
102587,6088571,Adorable One-Bed in Williamsburg!,20914678851,verified,Taylor,Brooklyn,Williamsburg,40.71687,-73.94656,United States,...,1.0,66.0,6/16/2019,1.35,2.0,1.0,352.0,• Check-in time is 2PM. Check-out time is 11am...,NaN,466.0
102588,6089124,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,...,1.0,177.0,6/29/2019,3.78,4.0,1.0,410.0,Keep the apartment clean and damage free please.,NaN,742.0

In [34]:
#24. Show all listings whose room_type is not “Private room”.

df[df['room type']=='Private room']

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,1159.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,744.0
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN,85.0
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN,1272.0
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN,1222.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102589,6089676,Lrg room 1 block from Prospect Park,74549151787,unconfirmed,Dave,Brooklyn,Flatbush,40.65231,-73.96189,United States,...,3.0,0.0,NaN,NaN,1.0,1.0,200.0,House Rules 1. Check-in is 4 pm local time. If...,NaN,367.0
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,1.0,8.0,9/6/2015,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...,NaN,1319.0
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,1013.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,1004.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN,1186.0

In [35]:
#25. Get listings where host_name starts with the letter “A”.

df[df['host name'].str.startswith('A', na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN,85.0
11,1007411,Beautiful 1br on Upper West Side,18824631834,verified,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,...,5.0,53.0,6/22/2019,0.43,4.0,1.0,163.0,"My ideal guests would be warm, friendly, and r...",NaN,727.0
18,1011277,Chelsea Perfect,73862528370,verified,Alberta,manhatan,Chelsea,40.74192,-73.99501,United States,...,1.0,260.0,7/1/2019,2.12,3.0,1.0,325.0,NaN,NaN,NaN
20,1012382,Huge 2 BR Upper East Cental Park,79805143117,verified,Audrey,Manhattan,East Harlem,40.79685,-73.94872,United States,...,7.0,0.0,NaN,NaN,3.0,2.0,347.0,"No smoking, No pets. No shoes in the house. V...",NaN,337.0
21,1012934,Sweet and Spacious Brooklyn Loft,86554611512,verified,Alissa,Brooklyn,Williamsburg,40.71842,-73.95718,United States,...,3.0,9.0,12/28/2021,0.07,3.0,1.0,193.0,- No smoking or open flames on the property - ...,NaN,572.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102508,6044940,3BR Gramercy Apt in heart of NYC,59749079462,verified,Alissa,Manhattan,Kips Bay,40.73912,-73.98250,United States,...,1.0,0.0,NaN,NaN,5.0,1.0,368.0,"We only ask that you have a ton of fun, and th...",NaN,512.0
102521,6052120,Must Love Dogs / Bushwick Brooklyn,22301937174,unconfirmed,Ange,Brooklyn,Bushwick,40.68802,-73.91474,United States,...,2.0,4.0,6/1/2019,0.19,5.0,1.0,407.0,Don't make noise in apt after 10pm. keep doors...,NaN,1000.0
102522,6052672,Sunny studio in the Upper East Side,16962195392,verified,Allie,Manhattan,Upper East Side,40.77138,-73.94809,United States,...,14.0,2.0,9/16/2017,0.06,5.0,1.0,350.0,Please Note: This unit was just renovated last...,NaN,590.0
102573,6080839,2BR apt. in converted church with large terrace,38845651458,verified,Annika,Brooklyn,Cobble Hill,40.68836,-73.99763,United States,...,6.0,6.0,10/27/2018,0.13,5.0,1.0,89.0,NaN,NaN,956.0
102581,6085258,Bright Bedroom in Bustling Bed Stuy Brooklyn,17339949163,unconfirmed,Amber,Brooklyn,Bedford-Stuyvesant,40.68742,-73.92825,United States,...,2.0,34.0,7/1/2019,0.70,5.0,3.0,299.0,It is a residential building so all of the res...,NaN,92.0

In [36]:
#26. Retrieve listings whose name ends with “Suite”.

df[df['NAME'].str.endswith(' suite',na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
2901,2603558,Classic Brownstone private suite,27275512510,verified,Elizabeth,Brooklyn,Bedford-Stuyvesant,40.68978,-73.93751,United States,...,2.0,189.0,6/30/2019,3.02,3.0,2.0,293.0,All I ask is that you are respectful of my hom...,NaN,1198.0
5233,3891522,cute convenient village suite,45916947898,verified,Ali,Manhattan,Greenwich Village,40.73110,-74.00014,United States,...,1.0,20.0,5/2/2019,0.40,NaN,1.0,382.0,During your stay please abide by the following...,NaN,730.0
7024,4880691,NYC New Years Penthouse suite,68184548374,verified,Howard,Manhattan,Midtown,40.76550,-73.98018,United States,...,3.0,1.0,11/11/2015,0.02,4.0,3.0,161.0,NaN,NaN,1297.0
14025,8747344,Master Bedroom w/ en suite,21983644710,verified,David,Queens,Astoria,40.76446,-73.92988,United States,...,2.0,0.0,NaN,NaN,4.0,1.0,83.0,No pets and no smoking (including outside near...,NaN,428.0
17738,10798033,Beautiful 2 bedroom private suite,62272685101,verified,Razia,Manhattan,Harlem,40.80297,-73.95050,United States,...,28.0,76.0,3/4/2019,2.16,1.0,2.0,296.0,We are looking for quiet and respectful guests...,NaN,347.0
18063,10977531,Private cozy suite,46016119236,verified,Gladys,Queens,Woodhaven,40.68904,-73.85052,United States,...,1.0,155.0,7/1/2019,4.34,1.0,1.0,173.0,NaN,NaN,379.0
19573,11811504,Carroll Gardens guest suite,65537311848,verified,Viki,Brooklyn,Carroll Gardens,40.68321,-73.99681,United States,...,2.0,116.0,6/23/2019,3.78,1.0,2.0,230.0,"No unexpected night guests, please No smoke in...",NaN,1163.0
21610,12936539,Private suite,18159221761,unconfirmed,Irisha,Queens,Fresh Meadows,40.74227,-73.78707,United States,...,1.0,26.0,7/8/2019,0.90,1.0,3.0,358.0,"This is our family home, not a rental that we ...",NaN,156.0
21802,13042581,Luxe Large Suite w/Views bathroom en suite,67452677857,verified,Cameron & Dione,Brooklyn,Downtown Brooklyn,40.69250,-73.98613,United States,...,3.0,28.0,6/9/2019,1.00,4.0,2.0,11.0,Our home is well cared for and loved. We would...,NaN,1046.0
32385,18887572,Royal suite,49183871363,unconfirmed,Voxie,Brooklyn,Canarsie,40.63202,-73.90916,United States,...,2.0,16.0,6/30/2019,1.21,5.0,1.0,358.0,Leave shoes by door No strong scents (perfumes...,NaN,689.0
36191,20989625,Gorgeous Cozy Brooklyn apartment suite,32931286922,verified,Chelsea,Queens,Ridgewood,40.70920,-73.91246,United States,...,1.0,0.0,NaN,NaN,5.0,1.0,0.0,Be respectful of all and communicate well enou...,NaN,1278.0
36874,21366846,Linden Estates Luxurious 2 bedroom suite,60222381896,unconfirmed,Sherley,Queens,St. Albans,40.69272,-73.76264,United States,...,2.0,2.0,1/1/2019,0.24,5.0,4.0,89.0,We kindly ask that you clean up after yourselv...,NaN,1223.0
37708,21827464,Airy Brooklyn Limestone: 2 bedroom suite,86132163215,unconfirmed,Billye And Joe,Brooklyn,Crown Heights,40.67133,-73.94631,United States,...,3.0,4.0,4/22/2019,0.56,3.0,2.0,89.0,Please treat the apartment like it is your own...,NaN,724.0
39135,22615597,Flushing downtown luxury suite,17428689655,unconfirmed,Vicky,Queens,Flushing,40.74449,-73.83476,United States,...,1.0,10.0,6/24/2019,1.41,4.0,6.0,169.0,Please expect to share the apartment with gues...,NaN,214.0
39250,22679111,Flushing downtown luxury suite,14948795941,verified,Vicky,Queens,Flushing,40.74390,-73.83261,United States,...,1.0,14.0,7/5/2019,1.97,3.0,6.0,138.0,1) No Smoking in property!!! 2) Do not slam d...,NaN,761.0
39261,22685186,Flushing downtown luxury suite,33331704750,verified,Vicky,Queens,Flushing,40.74548,-73.83410,United States,...,1.0,10.0,7/7/2019,1.59,4.0,6.0,163.0,NaN,NaN,523.0
41981,24187442,Beach suite,63133626069,unconfirmed,Anthony,Queens,Far Rockaway,40.59639,-73.74860,United States,...,4.0,20.0,6/30/2019,4.92,4.0,1.0,107.0,NaN,NaN,295.0
43631,25098737,Shar's Hideaway comfortable 1 bedroom suite,57559046922,unconfirmed,Sharon,Queens,Queens Village,40.70657,-73.72932,United States,...,1.0,1.0,4/20/2019,0.37,4.0,1.0,0.0,Check-in time is 1PM. Read the manual after yo...,NaN,374.0
43765,25172746,Comfy basement suite,64634847220,verified,Quisquella,Bronx,Woodlawn,40.90406,-73.86286,United States,...,1.0,1.0,7/4/2019,1.00,5.0,1.0,29.0,NaN,NaN,1021.0
46868,26886532,Beautiful large master bedroom suite,49032387461,unconfirmed,Fred,Brooklyn,South Slope,40.66512,-73.99084,United States,...,14.0,1.0,7/8/2019,1.00,5.0,1.0,26.0,NaN,NaN,1430.0
48233,27640422,Veneta New York suite,45500773217,verified,Gianluigi,Manhattan,Hell's Kitchen,40.76687,-73.98644,United States,...,1.0,0.0,NaN,NaN,4.0,1.0,364.0,Quiet hours are from midnight to 6 a.m. We as...,NaN,324.0
48919,28019300,Veneta New York suite,72921861984,unconfirmed,Gianluigi,Manhattan,Hell's Kitchen,40.76687,-73.98644,United States,...,1.0,0.0,NaN,NaN,3.0,1.0,364.0,NaN,NaN,1042.0
52426,29956216,Beach suite,30671528186,verified,Anthony,Queens,Far Rockaway,40.59650,-73.74879,United States,...,3.0,145.0,2/21/2022,3.98,2.0,1.0,135.0,NaN,NaN,1418.0
53700,30659846,Bohemian one bedroom guest suite,56800698454,unconfirmed,Gayle,Brooklyn,Crown Heights,40.66773,-73.95399,United States,...,4.0,20.0,2/16/2022,3.19,4.0,1.0,182.0,NaN,NaN,842.0
54038,30846523,Beautiful 2 bedroom private suite,36404216742,verified,Razia,Manhattan,Harlem,40.80350,-73.94918,United States,...,4.0,94.0,2/14/2022,1.39,2.0,2.0,71.0,NaN,NaN,900.0
54319,31001720,Carroll Gardens guest suite,54581951584,unconfirmed,Viki,Brooklyn,Cobble Hill,40.68455,-73.99739,United States,...,2.0,250.0,2/13/2022,3.97,2.0,2.0,158.0,NaN,NaN,256.0
56412,32157684,"VIP）Private bathroom, twin suite",86861431027,verified,Liqing,Queens,Flushing,40.74195,-73.81855,United States,...,30.0,19.0,1/26/2022,0.63,4.0,5.0,86.0,NaN,NaN,906.0
56841,32394620,The plush suite,70034777516,verified,Sean And Vanessa,Queens,Springfield Gardens,40.66446,-73.75251,United States,...,2.0,3.0,1/20/2022,0.56,3.0,4.0,54.0,NaN,NaN,613.0
58289,33194351,Cozy studio monthly suite,1999588534,verified,Michelle,Manhattan,Harlem,40.80718,-73.94536,United States,...,3.0,3.0,1/4/2022,0.37,3.0,11.0,340.0,NaN,NaN,1301.0
63760,36215984,TRYP by Wyndham Times Square - King suite,29757116125,verified,Vk,Manhattan,Chelsea,40.75279,-73.99508,United States,...,1.0,1.0,9/20/2021,0.18,4.0,26.0,59.0,NaN,NaN,998.0
63796,36235867,Lux&light 1 bedroom suite,42662076987,unconfirmed,Carlos,Brooklyn,Bushwick,40.69580,-73.91255,United States,...,30.0,10.0,9/18/2021,0.41,2.0,1.0,231.0,NaN,NaN,143.0
66838,37915963,有家客居75 This is a semi-basement suite,97411887461,verified,Xin,Queens,Flushing,40.74167,-73.81407,United States,...,30.0,5.0,9/9/2020,0.16,4.0,6.0,364.0,NaN,NaN,1061.0
67324,38184381,独栋别墅一房一厅独立套房private entrance twobeds garden s...,53610415779,unconfirmed,Jessica,Queens,Fresh Meadows,40.73380,-73.77937,United States,...,1.0,69.0,5/16/2020,2.15,3.0,2.0,125.0,NaN,NaN,878.0
67333,38189352,Private cozy suite,22641330731,unconfirmed,Gladys,Queens,Woodhaven,40.68938,-73.85167,United States,...,30.0,198.0,5/10/2020,2.91,3.0,1.0,1.0,NaN,NaN,529.0
68025,38571544,"The Great Escape, Private top floor suite",30957145985,unconfirmed,Aisha & Sherwin,Brooklyn,East New York,40.66603,-73.88550,United States,...,3.0,4.0,3/8/2020,0.16,4.0,1.0,248.0,NaN,NaN,120.0
71077,40257163,Classic Brownstone private suite,32786368228,unconfirmed,Elizabeth,Brooklyn,Bedford-Stuyvesant,40.68978,-73.93751,United States,...,2.0,189.0,6/30/2019,3.02,3.0,2.0,131.0,NaN,NaN,1198.0
74588,42196288,Beach suite,413054035,verified,Anthony,Queens,Far Rockaway,40.59639,-73.74860,United States,...,4.0,20.0,6/30/2019,4.92,4.0,1.0,107.0,NaN,NaN,295.0
76737,43383181,Carroll Gardens guest suite,22353880348,verified,Viki,Brooklyn,Carroll Gardens,40.68321,-73.99681,United States,...,2.0,116.0,6/23/2019,3.78,1.0,2.0,230.0,"No unexpected night guests, please No smoke in...",NaN,1163.0
78774,44508216,Private suite,24721306470,verified,Irisha,Queens,Fresh Meadows,40.74227,-73.78707,United States,...,1.0,26.0,7/8/2019,0.90,1.0,3.0,358.0,"This is our family home, not a rental that we ...",NaN,156.0
78966,44614258,Luxe Large Suite w/Views bathroom en suite,38632496262,unconfirmed,Cameron & Dione,Brooklyn,Downtown Brooklyn,40.69250,-73.98613,United States,...,3.0,28.0,6/9/2019,1.00,4.0,2.0,11.0,Our home is well cared for and loved. We would...,NaN,1046.0
87560,49360724,Beautiful 2 bedroom private suite,76920739342,verified,Razia,Manhattan,Harlem,40.80297,-73.95050,United States,...,28.0,76.0,3/4/2019,2.16,1.0,2.0,296.0,We are looking for quiet and respectful guests...,NaN,347.0
87885,49540222,Private cozy suite,3857956583,verified,Gladys,Queens,Woodhaven,40.68904,-73.85052,United States,...,1.0,155.0,7/1/2019,4.34,1.0,1.0,173.0,NaN,NaN,379.0
89395,50374195,Carroll Gardens guest suite,4499288861,unconfirmed,Viki,Brooklyn,Carroll Gardens,40.68321,-73.99681,United States,...,2.0,116.0,6/23/2019,3.78,1.0,2.0,230.0,"No unexpected night guests, please No smoke in...",NaN,1163.0
91432,51499230,Private suite,47335669596,verified,Irisha,Queens,Fresh Meadows,40.74227,-73.78707,United States,...,1.0,26.0,NaN,NaN,1.0,3.0,358.0,"This is our family home, not a rental that we ...",NaN,156.0
91624,51605271,Luxe Large Suite w/Views bathroom en suite,47850362545,verified,Cameron & Dione,Brooklyn,Downtown Brooklyn,40.69250,-73.98613,United States,...,3.0,28.0,6/9/2019,1.00,4.0,2.0,11.0,Our home is well cared for and loved. We would...,NaN,1046.0
95318,53645467,Royal suite,36907730252,verified,Voxie,Brooklyn,Canarsie,40.63202,-73.90916,United States,...,2.0,16.0,6/30/2019,1.21,5.0,1.0,358.0,Leave shoes by door No strong scents (perfumes...,NaN,689.0
99124,55747521,Gorgeous Cozy Brooklyn apartment suite,56160045466,unconfirmed,Chelsea,Queens,Ridgewood,40.70920,-73.91246,United States,...,1.0,0.0,NaN,NaN,5.0,1.0,0.0,Be respectful of all and communicate well enou...,NaN,1278.0
99660,56043554,Carroll Gardens guest suite,85525309827,verified,Viki,Brooklyn,Carroll Gardens,40.68321,-73.99681,United States,...,2.0,116.0,6/23/2019,3.78,1.0,2.0,230.0,"No unexpected night guests, please No smoke in...",NaN,1163.0
101697,57168589,Private suite,75274383984,unconfirmed,Irisha,Queens,Fresh Meadows,40.74227,-73.78707,United States,...,1.0,26.0,7/8/2019,0.90,1.0,3.0,358.0,"This is our family home, not a rental that we ...",NaN,156.0
101889,57274631,Luxe Large Suite w/Views bathroom en suite,31381154069,unconfirmed,Cameron & Dione,Brooklyn,Downtown Brooklyn,40.69250,-73.98613,United States,...,3.0,28.0,6/9/2019,1.00,4.0,2.0,11.0,Our home is well cared for and loved. We would...,NaN,1046.0

In [37]:
#27. Select listings that have both price > 150 and availability_365> 200.

df[(df['price']>150)&(df['availability 365']>200)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,1159.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,744.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,442.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,245.0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,692.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102590,6090228,Wonderful artists' loft in Brooklyn,9184535139,unconfirmed,Daniel,Brooklyn,Crown Heights,40.66673,-73.96127,United States,...,1.0,0.0,NaN,NaN,1.0,1.0,276.0,#NAME?,NaN,300.0
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,1013.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,1004.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN,1186.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN,655.0

In [38]:
#28. Filter listings where neighbourhood_group equals “Manhattan” and room_type equals “Entire home/apt”.

df[(df['neighbourhood group']=='Manhatten')&(df['room type']=='Entire home/apt')]

Empty DataFrame
Columns: [id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, last review, reviews per month, review rate number, calculated host listings count, availability 365, house_rules, license, a]
Index: []

[0 rows x 27 columns]

In [39]:
df['last review']

0         10/19/2021
1          5/21/2022
2                NaN
3           7/5/2019
4         11/19/2018
             ...
102594           NaN
102595      7/6/2015
102596           NaN
102597    10/11/2015
102598           NaN
Name: last review, Length: 102599, dtype: object

In [40]:
#29. Show all listings that were last reviewed in the year 2022. 

df['last review']=pd.to_datetime(df['last review'],errors='coerce')

df[df['last review'].dt.year==2022]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,170.0
103,1058223,Monkey Retreat Manhattan,62028601494,verified,Kelsey,Manhattan,Washington Heights,40.83927,-73.94281,United States,...,NaN,68.0,2022-01-02,0.60,NaN,1.0,393.0,Not many rules except there is no smoking,NaN,367.0
189,1105721,"LARGE, COMFY 1BDR W/CHARACTER!!!",5715989004,verified,Edgar,Brooklyn,Bedford-Stuyvesant,40.68237,-73.94150,United States,...,NaN,30.0,2022-03-02,0.29,NaN,1.0,NaN,NaN,NaN,209.0
230,1128365,"Nice, clean, safe, convenient 3BR",41153188173,unconfirmed,Fowler,Queens,Ridgewood,40.70411,-73.89934,United States,...,14.0,1.0,2022-04-03,0.01,5.0,5.0,80.0,-Remove shoes -be sure to lock the front door ...,NaN,787.0
316,1175863,Luxury 3 bed/ 2 bath apt in Harlem w/ terrace,44227072273,unconfirmed,Henderson,Manhattan,Harlem,40.80276,-73.95670,United States,...,14.0,31.0,2022-03-01,0.31,5.0,1.0,81.0,Please do not smoke in the house. If you smoke...,NaN,870.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69193,39216630,Cozy BX Home Away From Home ( 2 nd floor),76770057440,unconfirmed,Paulene,Bronx,Wakefield,40.88990,-73.85871,United States,...,4.0,48.0,2022-01-08,1.34,4.0,1.0,57.0,NaN,NaN,248.0
69275,39261919,Large Room w/ Private Entrance,59188125571,unconfirmed,Jacques,Brooklyn,Bedford-Stuyvesant,40.68905,-73.95410,United States,...,7.0,2.0,2022-05-05,0.02,5.0,3.0,0.0,NaN,NaN,204.0
69309,39280697,Rent in beautiful Sunnyside Gardens for holidays,25481131720,verified,Jazmin,Queens,Sunnyside,40.74679,-73.91853,United States,...,3.0,1.0,2022-04-04,0.01,2.0,1.0,330.0,NaN,NaN,412.0
69365,39311626,"Enjoy a 1 Bedroom to share, NYC",83703261637,unconfirmed,Catherine,Manhattan,Upper East Side,40.77799,-73.95223,United States,...,1.0,1.0,2022-01-02,0.01,2.0,1.0,0.0,NaN,NaN,481.0
69381,39320462,"Cozy, Hella Sunny, and Convenient!",76807548267,verified,Dennis,Brooklyn,Prospect Heights,40.67717,-73.96915,United States,...,30.0,1.0,2022-03-01,0.01,1.0,1.0,341.0,NaN,NaN,972.0

In [41]:
#30 Display all listings where the name column contains 'Downtown'

df[df['NAME'].str.contains('Downtown',na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
41,1023980,ENJOY Downtown NYC!,63131487263,unconfirmed,Byron,Manhattan,East Village,40.72290,-73.98199,United States,...,2.0,245.0,2019-06-21,2.08,3.0,2.0,354.0,NaN,NaN,676.0
274,1152666,ENJOY Downtown NYC!!,7784280062,verified,Gibson,Manhattan,East Village,40.72321,-73.98157,United States,...,2.0,203.0,2019-06-23,1.96,3.0,2.0,NaN,"No smoking inside. Be tidy, we don't have a ma...",NaN,511.0
487,1270306,Very close to Downtown Awesome Private Apartment,7445813909,unconfirmed,Antony,Brooklyn,Gravesend,40.60452,-73.97103,United States,...,7.0,0.0,NaT,NaN,NaN,2.0,159.0,NaN,NaN,914.0
516,1286323,Comfort at Crossroads of Downtown,82992556236,verified,Kevin,Manhattan,Chelsea,40.73862,-73.99758,NaN,...,1.0,2.0,2015-08-28,0.02,2.0,1.0,256.0,"We expect our guests to be honest, to treat ou...",NaN,NaN
605,1335478,Great Bedroom in Downtown Manhattan,39482467591,unconfirmed,Alberta,Manhattan,Chinatown,40.71611,-73.99828,United States,...,30.0,59.0,2019-06-24,0.64,3.0,1.0,211.0,Please remember that this is a residential bui...,NaN,143.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102043,57359685,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,verified,NaN,Manhattan,SoHo,40.72318,-74.00223,United States,...,2.0,21.0,2019-07-01,0.74,4.0,2.0,343.0,#NAME?,NaN,1252.0
102129,35546044,The Residences at W New York - Downtown - Apt 27D,43741555866,unconfirmed,Zeus,Manhattan,Financial District,40.71035,-74.01427,United States,...,30.0,2.0,2021-11-09,0.10,NaN,34.0,333.0,NaN,NaN,193.0
102426,20384857,Charming 3bed/2ba Downtown/LES,55829170118,unconfirmed,Anastasia,Manhattan,Lower East Side,40.71815,-73.98213,United States,...,3.0,6.0,2019-03-31,0.87,5.0,1.0,67.0,- We have a lovable and very social black lab ...,NaN,998.0
102429,20386514,Huge Room for Nightly Stays Downtown or Monthly,44994616102,verified,Abbey,Manhattan,Tribeca,40.71810,-74.00999,United States,...,5.0,3.0,2019-05-21,0.30,3.0,1.0,95.0,No pets No alcohol,NaN,1225.0
102561,6074212,NO FEE RENTAL *Lease Takeover Modern Apt Downtown,60627453207,verified,Monica,Manhattan,Financial District,40.70809,-74.00170,United States,...,1.0,0.0,NaT,NaN,3.0,1.0,286.0,Please don't fiddle around with my stuff or an...,NaN,1027.0

In [42]:
#31 retrieve listings where reviews_per_month is greater than 2

df[df['reviews per month']>2]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,30.0,270.0,2019-07-05,4.64,4.0,1.0,322.0,NaN,NaN,442.0
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,2.0,430.0,2019-06-24,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN,1222.0
18,1011277,Chelsea Perfect,73862528370,verified,Alberta,manhatan,Chelsea,40.74192,-73.99501,United States,...,1.0,260.0,2019-07-01,2.12,3.0,1.0,325.0,NaN,NaN,NaN
19,1011830,Hip Historic Brownstone Apartment with Backyard,72145018858,NaN,Martin,Brooklyn,Crown Heights,40.67592,-73.94694,United States,...,3.0,53.0,2019-06-22,4.44,5.0,1.0,345.0,LAUNDRY - Laundry can be done by the visitor b...,NaN,NaN
31,1018457,front room/double bed,69410526955,unconfirmed,Byron,Manhattan,Harlem,40.82245,-73.95104,United States,...,3.0,242.0,2019-06-01,2.04,NaN,3.0,105.0,No loud noises or loud music. Please help us s...,NaN,924.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102569,6078630,"Elegant 1BR, Private Bath in Brownstone",37385825013,verified,Emily And Joel,Brooklyn,Park Slope,40.66880,-73.97865,United States,...,1.0,184.0,2019-02-10,3.86,4.0,4.0,407.0,NO Smoking,NaN,1182.0
102575,6081944,NYC Chauncey 2 .20 min to manhattan,26326930315,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.68237,-73.91977,United States,...,1.0,123.0,2019-03-17,2.95,2.0,4.0,200.0,NO Smoking Pets Allowed with a $375 non refund...,NaN,722.0
102579,6084153,Alexander's 2BR Luxury Quarters,32736284559,verified,Juan,Brooklyn,Bedford-Stuyvesant,40.68740,-73.93830,United States,...,3.0,123.0,2019-06-26,2.53,4.0,1.0,203.0,NaN,NaN,353.0
102580,6084705,"Near LGA, Citifield, US Open Tennis",97606085736,verified,Carmen,Queens,East Elmhurst,40.76578,-73.86424,United States,...,1.0,209.0,2019-06-11,4.38,3.0,1.0,270.0,House Rules 1. Check-in is 4 pm local time. If...,NaN,731.0
102588,6089124,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,...,1.0,177.0,2019-06-29,3.78,4.0,1.0,410.0,Keep the apartment clean and damage free please.,NaN,742.0

In [43]:
#32 select listings where host_id appers more than once

df[df['host id'].duplicated(keep=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
9098,6026161,Upper East Side 2 bedroom- close to Hospitals-,65193709566,verified,Juliana,Manhattan,Upper East Side,40.76222,-73.96030,United States,...,30.0,2.0,2019-06-08,0.21,3.0,34.0,157.0,NaN,NaN,126.0
9099,6026714,Close to East Side Hospitals- Modern 2 Bedroom...,31072202372,verified,Juliana,Manhattan,Upper East Side,40.76249,-73.96217,United States,...,30.0,6.0,2019-01-31,0.14,3.0,34.0,67.0,"The quieter the better, but otherwise make you...",NaN,342.0
9100,6027266,ACADIA Spacious 2 Bedroom Apt - Close to Hospi...,95854111798,verified,Juliana,Manhattan,Upper East Side,40.76021,-73.96157,United States,...,30.0,10.0,2018-11-18,0.22,5.0,34.0,211.0,No Smoking No Pets,NaN,703.0
9101,6027818,*ENCHANTMENT* Upper East Side 2 bedroom- Sunny!,73401481508,unconfirmed,Juliana,Manhattan,Upper East Side,40.76244,-73.96031,United States,...,30.0,9.0,2018-09-30,0.20,5.0,34.0,411.0,Please treat it as it were your own home and b...,NaN,647.0
9102,6028371,*JAMES* Amazing Spacious 2 Bedroom- Bright!,37678424985,verified,Juliana,Manhattan,Upper East Side,40.76035,-73.96133,United States,...,30.0,8.0,2019-06-11,0.27,4.0,34.0,411.0,Be courteous and respectful to people in the h...,NaN,967.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,1.0,0.0,NaT,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,1013.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,1.0,2015-07-06,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,1004.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,3.0,0.0,NaT,NaN,5.0,1.0,342.0,NaN,NaN,1186.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2.0,5.0,2015-10-11,0.10,3.0,1.0,386.0,NaN,NaN,655.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,1.0,0.0,NaT,NaN,3.0,1.0,69.0,NaN,NaN,1238.0

In [44]:
#33 filter all listing that not located in 'Brooklyn'

df[df['neighbourhood group']!='Brooklyn']

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,170.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,3.0,0.0,NaT,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,744.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,245.0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,3.0,74.0,2019-06-22,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,692.0
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,2.0,430.0,2019-06-24,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN,1222.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102592,6091333,3BR/1 Ba in TriBeCa w/ outdoor deck,53266862889,unconfirmed,Nick,Manhattan,Tribeca,40.71845,-74.01183,United States,...,1.0,0.0,NaT,NaN,2.0,1.0,177.0,Guests should treat my home as if it were thei...,NaN,944.0
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,1.0,8.0,2015-09-06,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...,NaN,1319.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,1.0,2015-07-06,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,1004.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2.0,5.0,2015-10-11,0.10,3.0,1.0,386.0,NaN,NaN,655.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,1.0,0.0,NaT,NaN,3.0,1.0,69.0,NaN,NaN,1238.0

In [45]:
#34 Retrive listings where city column contains 'York'

df[df['NAME'].str.contains('York',na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
52,1030056,Cozy 1BD on Central Park West in New York City,50562514538,unconfirmed,Madaline,Manhattan,Upper West Side,40.78635,-73.97008,United States,...,NaN,73.0,2019-07-07,0.63,3.0,1.0,NaN,No smoking anywhere on the property. Quiet and...,NaN,1081.0
170,1095227,New York room with a view,95792367490,NaN,Dexter,Staten Island,St. George,40.64524,-74.08088,United States,...,131.0,166.0,2019-06-13,1.66,4.0,1.0,-1.0,Please tell me about who you will be traveling...,NaN,1218.0
397,1220599,Authentic New York City Living,5274414000,verified,Allen,Brooklyn,Bedford-Stuyvesant,40.68569,-73.93038,United States,...,2.0,38.0,2019-06-03,0.54,3.0,2.0,107.0,This is a no-smoking apartment. If you do smok...,NaN,158.0
522,1289637,Family & Friends in New York City,9750353852,unconfirmed,Emma,Brooklyn,East New York,40.67497,-73.87305,United States,...,3.0,177.0,2019-06-29,1.86,2.0,1.0,145.0,Overall please treat the apartment as you woul...,NaN,1417.0
707,1391812,NewYork Modern Pre-War LoftStudio,21342091752,unconfirmed,Anderson,Manhattan,Upper East Side,40.76928,-73.95021,United States,...,2.0,314.0,2019-07-01,3.45,4.0,2.0,388.0,"I only accept clean people , reliable, no smok...",NaN,913.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102405,20373259,"New York, Jackson heights",46551322242,verified,Freddy,Queens,Jackson Heights,40.75395,-73.87396,United States,...,1.0,5.0,2019-01-02,0.47,2.0,1.0,180.0,NaN,NaN,241.0
102409,20375468,New York Home,8619760998,unconfirmed,Elena,Manhattan,Washington Heights,40.83341,-73.94154,United States,...,3.0,6.0,2019-06-19,0.95,4.0,6.0,46.0,NaN,NaN,544.0
102411,20376572,"Visit New York,The Local Brooklyn Way SuperHost",70255726896,unconfirmed,Paul,Queens,Ridgewood,40.70186,-73.90467,United States,...,1.0,48.0,2019-06-22,4.50,3.0,1.0,171.0,"Please, no smoking inside the building or on t...",NaN,72.0
102462,20404740,New York Apartment,98342871281,unconfirmed,Karen,Manhattan,Civic Center,40.71310,-74.00527,United States,...,15.0,0.0,NaT,NaN,3.0,1.0,0.0,"NO SMOKING, please stop smoking a block away s...",NaN,1331.0
102489,6034446,Book Now & Save: Spend July in New York City!,3016524636,unconfirmed,Lou,Queens,Astoria,40.76583,-73.91086,United States,...,1.0,108.0,2019-06-06,2.23,1.0,4.0,225.0,NaN,NaN,1339.0

In [46]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'a'],
      dtype='object')

In [47]:
#35 get all listings thet have price greater than the avg price
import re
df['price'] = pd.to_numeric(df['price'].str.extract(r'(\d+\.?\d*)')[0])

AttributeError: Can only use .str accessor with string values!

In [ ]:
import math
df[df['price']>df['price'].mean()]

In [48]:
#displat listings eith minimum_niights exactly equals to 7

df[df['minimum nights']==7]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
20,1012382,Huge 2 BR Upper East Cental Park,79805143117,verified,Audrey,Manhattan,East Harlem,40.79685,-73.94872,United States,...,7.0,0.0,NaT,NaN,3.0,2.0,347.0,"No smoking, No pets. No shoes in the house. V...",NaN,337.0
43,1025085,1bdr w private bath. in lofty apt,45597582469,NaN,Charlie,Brooklyn,Fort Greene,40.69673,-73.97584,United States,...,7.0,25.0,2018-09-30,0.23,1.0,1.0,405.0,"No smoking, No pets. No shoes in the house. Vi...",NaN,824.0
45,1026190,BEST BET IN HARLEM,2107606817,unconfirmed,Chester,Manhattan,Harlem,40.81175,-73.94478,United States,...,7.0,97.0,2019-06-13,0.84,NaN,1.0,152.0,- Quiet hours between 10pm-6am - Visitors in c...,NaN,74.0
65,1037236,Double Room w Private Deck Clinton Hill Best Area,71078326464,unconfirmed,William,Brooklyn,Clinton Hill,40.69000,-73.96788,United States,...,7.0,27.0,2017-09-30,0.23,2.0,2.0,NaN,NaN,NaN,990.0
73,1041654,Cool Room in Hell's Kitchen,44843744875,verified,Charlie,Manhattan,Hell's Kitchen,40.76342,-73.98865,United States,...,7.0,23.0,2019-06-01,0.43,3.0,1.0,NaN,NaN,NaN,724.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102545,6065375,Loft rental off of Graham!,24747380997,unconfirmed,Frances,Brooklyn,Williamsburg,40.71303,-73.94063,United States,...,7.0,2.0,2016-08-23,0.04,2.0,1.0,374.0,NaN,NaN,1130.0
102553,6069793,"Custom Designed Cozy Garden Apt,",7756381071,unconfirmed,Jean& Toney,Brooklyn,Canarsie,40.64574,-73.90781,United States,...,7.0,0.0,NaT,NaN,4.0,3.0,95.0,"- Absolutely no smoking in, on or near the pro...",NaN,244.0
102555,6070898,Sublet entire apt in Brooklyn,83573592009,unconfirmed,Laszlo Jakab,Brooklyn,Brooklyn Heights,40.69382,-73.99334,United States,...,7.0,1.0,2015-06-29,0.02,4.0,1.0,299.0,No smoking in the unit or in the building (str...,NaN,668.0
102568,6078078,Furnished Bedroom in 2 Bedroom apt.,43698780331,verified,Etkin,Queens,Long Island City,40.75600,-73.92050,United States,...,7.0,0.0,NaT,NaN,4.0,1.0,34.0,NaN,NaN,1259.0
102582,6085810,Private room in the best part of BK,4746552394,verified,Brad,Brooklyn,Crown Heights,40.66743,-73.94712,United States,...,7.0,49.0,2019-06-01,1.01,2.0,1.0,425.0,No Smoking. Pets Allowed with fee.,NaN,619.0

In [49]:
#37 SELCT LISTINGS with even number of minimum nights

df[df['minimum nights']%2==0]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,2021-10-19,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,1159.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,170.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,30.0,270.0,2019-07-05,4.64,4.0,1.0,322.0,NaN,NaN,442.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,245.0
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,2.0,430.0,2019-06-24,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN,1222.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102577,6083048,Gigantic Private Brooklyn Apartment,55330806381,verified,Nikki,Brooklyn,Greenpoint,40.72442,-73.93957,United States,...,10.0,2.0,2016-07-06,0.04,1.0,1.0,33.0,NaN,NaN,833.0
102581,6085258,Bright Bedroom in Bustling Bed Stuy Brooklyn,17339949163,unconfirmed,Amber,Brooklyn,Bedford-Stuyvesant,40.68742,-73.92825,United States,...,2.0,34.0,2019-07-01,0.70,5.0,3.0,299.0,It is a residential building so all of the res...,NaN,92.0
102584,6086914,2 block walk from the beach in NYC,70051719594,verified,Vladimir,Queens,Arverne,40.59270,-73.78990,United States,...,2.0,89.0,2019-05-26,1.82,2.0,1.0,394.0,NaN,NaN,679.0
102586,6088019,Patio Oasis in Upper East Side,41141109074,verified,Margaret,Manhattan,Upper East Side,40.77703,-73.94773,United States,...,4.0,8.0,2016-08-08,0.17,5.0,1.0,159.0,- NO SMOKING (You'll have to do that outside i...,NaN,250.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2.0,5.0,2015-10-11,0.10,3.0,1.0,386.0,NaN,NaN,655.0

In [50]:
#38 retrieve all listings whose host name length is more than 10 chars

def foo(x):
    
    if len(str(x))>10:
        return True
    else:
        return False
df[df['host name'].apply(foo)]

#     df[df['host name'].str.len()>10]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
1073,1593954,Serene Room...,49750343850,verified,Maria Luiza,Brooklyn,Sunset Park,40.63970,-74.01620,United States,...,7.0,28.0,2019-05-12,0.32,2.0,2.0,160.0,For Your CarYup! IT'S JUST THE PARKING SPACE. ...,NaN,571.0
1091,1603895,"Cozy private room, williamsburg NYC",71939962014,verified,Javier & Jorge,Brooklyn,Williamsburg,40.70610,-73.94531,United States,...,4.0,132.0,2019-06-10,1.51,3.0,2.0,407.0,*Please share with other guests in your reserv...,NaN,840.0
1100,1608866,Sunny plant-filled apartment with 2 balconies,81188620051,unconfirmed,Ora & Scout,Brooklyn,Crown Heights,40.67615,-73.95441,United States,...,2.0,35.0,2018-01-01,0.54,4.0,3.0,277.0,House Rules 1. Check-in is 4 pm local time. If...,NaN,482.0
1102,1609971,"Bright, Bedstuy Gem",14399757070,verified,Nicole Lavonne,Brooklyn,Bedford-Stuyvesant,40.68944,-73.93760,United States,...,3.0,182.0,2019-07-01,2.15,4.0,1.0,-1.0,House Rules 1. Check-in is 4 pm local time. If...,NaN,180.0
1113,1616046,Gorgeous Summer Duplex/Yard sublet,9729014487,unconfirmed,Verena And Dylan,Brooklyn,Bedford-Stuyvesant,40.68229,-73.94287,United States,...,14.0,3.0,2013-09-01,0.04,4.0,1.0,338.0,NaN,NaN,1145.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102518,6050463,Beautiful apartment in awesome Clinton Hill!,18401849962,unconfirmed,Xristina&Keith,Brooklyn,Bedford-Stuyvesant,40.69213,-73.95869,United States,...,15.0,5.0,2019-05-20,0.26,4.0,1.0,421.0,No smoking. No pets. Children under 18 to be s...,NaN,73.0
102553,6069793,"Custom Designed Cozy Garden Apt,",7756381071,unconfirmed,Jean& Toney,Brooklyn,Canarsie,40.64574,-73.90781,United States,...,7.0,0.0,NaT,NaN,4.0,3.0,95.0,"- Absolutely no smoking in, on or near the pro...",NaN,244.0
102555,6070898,Sublet entire apt in Brooklyn,83573592009,unconfirmed,Laszlo Jakab,Brooklyn,Brooklyn Heights,40.69382,-73.99334,United States,...,7.0,1.0,2015-06-29,0.02,4.0,1.0,299.0,No smoking in the unit or in the building (str...,NaN,668.0
102569,6078630,"Elegant 1BR, Private Bath in Brownstone",37385825013,verified,Emily And Joel,Brooklyn,Park Slope,40.66880,-73.97865,United States,...,1.0,184.0,2019-02-10,3.86,4.0,4.0,407.0,NO Smoking,NaN,1182.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2.0,5.0,2015-10-11,0.10,3.0,1.0,386.0,NaN,NaN,655.0

In [51]:
#39 filter listings where price is a multiple of 50

df[df['price']%50==0]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
23,1014039,CBG Helps Haiti Room#2.5,87668933180,NaN,William,Brooklyn,Park Slope,40.67989,-73.97798,United States,...,1.0,39.0,2019-01-01,0.37,3.0,6.0,9.0,NaN,NaN,1260.0
107,1060432,Large 2 Bedroom Great for Groups!,94662871331,unconfirmed,Tess,Brooklyn,Bedford-Stuyvesant,40.68373,-73.92377,United States,...,90.0,162.0,2019-06-28,1.46,3.0,2.0,189.0,- Thanks for not smoking and leaving your pets...,NaN,600.0
165,1092466,Charming & Cozy midtown loft any WEEK ENDS !!!,3310140241,verified,Luke,Manhattan,Upper East Side,40.76123,-73.96420,United States,...,81.0,4.0,2016-09-23,NaN,1.0,1.0,335.0,Please be respectful. Keep noise to a minimum...,NaN,1140.0
183,1102407,Couldn't Be Closer To Columbia Uni,44580630332,unconfirmed,Bruce,Manhattan,Morningside Heights,40.80549,-73.95924,United States,...,110.0,122.0,2019-05-14,1.18,4.0,2.0,425.0,NaN,NaN,540.0
278,1154875,CHARMING EAST VILLAGE 2 (or 1) BR,18425219763,unconfirmed,Chapman,Manhattan,East Village,40.72956,-73.98158,United States,...,7.0,5.0,2019-01-03,0.15,4.0,1.0,33.0,Thanks for not smoking and leaving your pets a...,NaN,1020.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102320,20326313,Spacious room in awesome Bushwick townhouse,31263630543,unconfirmed,Sebastien,Brooklyn,Bushwick,40.69194,-73.92352,United States,...,3.0,1.0,2018-08-29,0.10,3.0,1.0,0.0,NaN,NaN,660.0
102394,20367183,Sonder | Madison Ave | Modern 1BR + Gym,94899572175,verified,Sonder,Manhattan,Midtown,40.74705,-73.98268,United States,...,29.0,0.0,NaT,NaN,2.0,96.0,328.0,I'll guide you with everything upon check-in,NaN,1200.0
102414,20378229,Morningside Heights Cozy & Clean Modern Apt.,20091049290,verified,Krystalee,Manhattan,Harlem,40.80624,-73.95622,United States,...,1.0,1.0,2018-08-31,0.10,3.0,1.0,0.0,"Respect yourself, respect others, clean up aft...",NaN,600.0
102503,6042178,"Perfect for Cat, Book, Park Lovers!",17949645201,verified,Laura,Brooklyn,Flatbush,40.65371,-73.95623,United States,...,2.0,12.0,2015-12-19,0.25,1.0,1.0,0.0,No smoking in the unit or in the building (str...,NaN,480.0
102590,6090228,Wonderful artists' loft in Brooklyn,9184535139,unconfirmed,Daniel,Brooklyn,Crown Heights,40.66673,-73.96127,United States,...,1.0,0.0,NaT,NaN,1.0,1.0,276.0,#NAME?,NaN,300.0

In [52]:
#40 show names with having more than 3 words

def foo(x):
    a=str(x).split()
    if len(a)>3:
        return True
    else:
        return False

df[df['NAME'].apply(foo)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,2021-10-19,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,1159.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,3.0,0.0,NaT,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,744.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,245.0
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,3.0,74.0,2019-06-22,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,692.0
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,2.0,430.0,2019-06-24,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN,1222.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,1.0,0.0,NaT,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,1013.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,1.0,2015-07-06,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,1004.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,3.0,0.0,NaT,NaN,5.0,1.0,342.0,NaN,NaN,1186.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2.0,5.0,2015-10-11,0.10,3.0,1.0,386.0,NaN,NaN,655.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,1.0,0.0,NaT,NaN,3.0,1.0,69.0,NaN,NaN,1238.0

In [53]:
#41rename the column neighbourhood_group to region



df=df.rename(columns={'neighbourhood group':'region'})

In [54]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'region', 'neighbourhood', 'lat', 'long', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'a'],
      dtype='object')

In [55]:
#42 add a new column price_per_review=price/number_of_review
import numpy as np
df['ppr']=df['price']/df['number of reviews'].replace(0,np.nan)

In [56]:
df

,id,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,country,...,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a,ppr
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,9.0,2021-10-19,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,1159.0,107.333333
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,45.0,2022-05-21,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,170.0,3.155556
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,0.0,NaT,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,744.0,NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,270.0,2019-07-05,4.64,4.0,1.0,322.0,NaN,NaN,442.0,1.362963
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,9.0,2018-11-19,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,245.0,22.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,0.0,NaT,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,1013.0,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,2015-07-06,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,1004.0,837.000000
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,0.0,NaT,NaN,5.0,1.0,342.0,NaN,NaN,1186.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,5.0,2015-10-11,0.10,3.0,1.0,386.0,NaN,NaN,655.0,109.200000
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,0.0,NaT,NaN,3.0,1.0,69.0,NaN,NaN,1238.0,NaN

In [57]:
df['price'].max()

1200.0

In [58]:
#43 create a column price_category as 'Low','Medium',or 'High' based on price ranges

def foo(x):
    if pd.isna(x):
        return 'Unknown'
    if x<=250:
        return 'low'
    elif x>250 and x<800:
        return 'Medium'
    else:
        return 'High'

df['Price_cat']=df['price'].apply(foo)

In [59]:
df

,id,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,country,...,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a,ppr,Price_cat
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,2021-10-19,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,1159.0,107.333333,High
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,2022-05-21,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,170.0,3.155556,low
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,NaT,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,744.0,NaN,Medium
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,2019-07-05,4.64,4.0,1.0,322.0,NaN,NaN,442.0,1.362963,Medium
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,2018-11-19,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,245.0,22.666667,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,NaT,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,1013.0,NaN,High
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,2015-07-06,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,1004.0,837.000000,High
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,NaT,NaN,5.0,1.0,342.0,NaN,NaN,1186.0,NaN,High
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2015-10-11,0.10,3.0,1.0,386.0,NaN,NaN,655.0,109.200000,Medium
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,NaT,NaN,3.0,1.0,69.0,NaN,NaN,1238.0,NaN,High

In [60]:
#44 add a column showing the length of each listings name

df['lenName']=df['NAME'].str.len()

In [61]:
df

,id,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,country,...,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,a,ppr,Price_cat,lenName
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,1159.0,107.333333,High,34.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,170.0,3.155556,low,21.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,744.0,NaN,Medium,35.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,4.64,4.0,1.0,322.0,NaN,NaN,442.0,1.362963,Medium,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,245.0,22.666667,low,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,1013.0,NaN,High,26.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,1004.0,837.000000,High,29.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,NaN,5.0,1.0,342.0,NaN,NaN,1186.0,NaN,High,30.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,0.10,3.0,1.0,386.0,NaN,NaN,655.0,109.200000,Medium,32.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,NaN,3.0,1.0,69.0,NaN,NaN,1238.0,NaN,High,20.0

In [62]:
#45 Combine city AND NEIGHBOURHOOD INTO A new location

df['location']=df['neighbourhood']+' , '+df['region']

In [63]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'region', 'neighbourhood', 'lat', 'long', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'a', 'ppr', 'Price_cat',
       'lenName', 'location'],
      dtype='object')

In [64]:
#46 extract the year from last_review int a new column full_location

df['year']=df['last review'].dt.year

In [65]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'region', 'neighbourhood', 'lat', 'long', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'a', 'ppr', 'Price_cat',
       'lenName', 'location', 'year'],
      dtype='object')

In [66]:
(df['reviews per month']>1).sum()

36218

In [67]:
#47. Round all values in the reviews_per_month column to 2 decimal places.
import numpy as np
def foo(x):
    if pd.isna(x):
        return x
    else:
        x = x * 100
        x = int(x + 0.5)
        return x / 100
        
df['reviews per month']=df['reviews per month'].apply(foo)

In [68]:
df['reviews per month']

0         0.21
1         0.38
2          NaN
3         4.64
4         0.10
          ...
102594     NaN
102595    0.02
102596     NaN
102597    0.10
102598     NaN
Name: reviews per month, Length: 102599, dtype: float64

In [69]:
#48. Replace all spaces in column names with underscores.

df['NAME1']=df['NAME'].replace(' ','_',regex=True)

In [70]:
df

,id,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,country,...,availability 365,house_rules,license,a,ppr,Price_cat,lenName,location,year,NAME1
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,286.0,Clean up and treat the home the way you'd like...,NaN,1159.0,107.333333,High,34.0,"Kensington , Brooklyn",2021.0,Clean_&_quiet_apt_home_by_the_park
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,228.0,Pet friendly but please confirm with me if the...,NaN,170.0,3.155556,low,21.0,"Midtown , Manhattan",2022.0,Skylit_Midtown_Castle
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,352.0,"I encourage you to use my kitchen, cooking and...",NaN,744.0,NaN,Medium,35.0,"Harlem , Manhattan",NaN,THE_VILLAGE_OF_HARLEM....NEW_YORK_!
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,322.0,NaN,NaN,442.0,1.362963,Medium,NaN,"Clinton Hill , Brooklyn",2019.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,289.0,"Please no smoking in the house, porch or on th...",NaN,245.0,22.666667,low,48.0,"East Harlem , Manhattan",2018.0,Entire_Apt:_Spacious_Studio/Loft_by_central_park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,1013.0,NaN,High,26.0,"Williamsburg , Brooklyn",NaN,Spare_room_in_Williamsburg
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,395.0,House rules: Guests agree to the following ter...,NaN,1004.0,837.000000,High,29.0,"Morningside Heights , Manhattan",2015.0,Best_Location_near_Columbia_U
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,342.0,NaN,NaN,1186.0,NaN,High,30.0,"Park Slope , Brooklyn",NaN,"Comfy,_bright_room_in_Brooklyn"
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,386.0,NaN,NaN,655.0,109.200000,Medium,32.0,"Long Island City , Queens",2015.0,Big_Studio-One_Stop_from_Midtown
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,69.0,NaN,NaN,1238.0,NaN,High,20.0,"Upper West Side , Manhattan",NaN,585_sf_Luxury_Studio

In [71]:
#49. Create a column is_available that is True if availability_365 > 0, else False.

df['is_available']=df['availability 365'].apply(lambda x : True if x>0 else False)

In [72]:
#50 50. Change all text in room_type to uppercase.

df['NAME1']=df['NAME1'].str.upper()

In [73]:
#51. Create a column price_in_inr assuming 1 USD = 83 INR.

In [74]:
import re
df['price']=df['price'].str.extract(r'(\d+\.?\d+)')

AttributeError: Can only use .str accessor with string values!

In [75]:
df['INRprice']=df['price'].astype(float)*83

In [76]:
df['INRprice']

0         80178.0
1         11786.0
2         51460.0
3         30544.0
4         16932.0
           ...
102594    70052.0
102595    69471.0
102596    82004.0
102597    45318.0
102598    85656.0
Name: INRprice, Length: 102599, dtype: float64

In [77]:
#52. Reorder columns so that price comes first.
df = df[['price'] + [col for col in df.columns if col != 'price']]

In [78]:
df

,price,id,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,...,license,a,ppr,Price_cat,lenName,location,year,NAME1,is_available,INRprice
0,966.0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,NaN,1159.0,107.333333,High,34.0,"Kensington , Brooklyn",2021.0,CLEAN_&_QUIET_APT_HOME_BY_THE_PARK,True,80178.0
1,142.0,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,NaN,170.0,3.155556,low,21.0,"Midtown , Manhattan",2022.0,SKYLIT_MIDTOWN_CASTLE,True,11786.0
2,620.0,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,...,NaN,744.0,NaN,Medium,35.0,"Harlem , Manhattan",NaN,THE_VILLAGE_OF_HARLEM....NEW_YORK_!,True,51460.0
3,368.0,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,...,NaN,442.0,1.362963,Medium,NaN,"Clinton Hill , Brooklyn",2019.0,NaN,True,30544.0
4,204.0,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,NaN,245.0,22.666667,low,48.0,"East Harlem , Manhattan",2018.0,ENTIRE_APT:_SPACIOUS_STUDIO/LOFT_BY_CENTRAL_PARK,True,16932.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844.0,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,...,NaN,1013.0,NaN,High,26.0,"Williamsburg , Brooklyn",NaN,SPARE_ROOM_IN_WILLIAMSBURG,True,70052.0
102595,837.0,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,...,NaN,1004.0,837.000000,High,29.0,"Morningside Heights , Manhattan",2015.0,BEST_LOCATION_NEAR_COLUMBIA_U,True,69471.0
102596,988.0,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,...,NaN,1186.0,NaN,High,30.0,"Park Slope , Brooklyn",NaN,"COMFY,_BRIGHT_ROOM_IN_BROOKLYN",True,82004.0
102597,546.0,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,...,NaN,655.0,109.200000,Medium,32.0,"Long Island City , Queens",2015.0,BIG_STUDIO-ONE_STOP_FROM_MIDTOWN,True,45318.0
102598,1032.0,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,...,NaN,1238.0,NaN,High,20.0,"Upper West Side , Manhattan",NaN,585_SF_LUXURY_STUDIO,True,85656.0

In [79]:
#53. Drop the id column from the dataset.

df.drop(columns=['id'])

,price,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,country,...,license,a,ppr,Price_cat,lenName,location,year,NAME1,is_available,INRprice
0,966.0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,NaN,1159.0,107.333333,High,34.0,"Kensington , Brooklyn",2021.0,CLEAN_&_QUIET_APT_HOME_BY_THE_PARK,True,80178.0
1,142.0,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,NaN,170.0,3.155556,low,21.0,"Midtown , Manhattan",2022.0,SKYLIT_MIDTOWN_CASTLE,True,11786.0
2,620.0,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,NaN,744.0,NaN,Medium,35.0,"Harlem , Manhattan",NaN,THE_VILLAGE_OF_HARLEM....NEW_YORK_!,True,51460.0
3,368.0,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,NaN,442.0,1.362963,Medium,NaN,"Clinton Hill , Brooklyn",2019.0,NaN,True,30544.0
4,204.0,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,NaN,245.0,22.666667,low,48.0,"East Harlem , Manhattan",2018.0,ENTIRE_APT:_SPACIOUS_STUDIO/LOFT_BY_CENTRAL_PARK,True,16932.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844.0,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,NaN,1013.0,NaN,High,26.0,"Williamsburg , Brooklyn",NaN,SPARE_ROOM_IN_WILLIAMSBURG,True,70052.0
102595,837.0,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,NaN,1004.0,837.000000,High,29.0,"Morningside Heights , Manhattan",2015.0,BEST_LOCATION_NEAR_COLUMBIA_U,True,69471.0
102596,988.0,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,NaN,1186.0,NaN,High,30.0,"Park Slope , Brooklyn",NaN,"COMFY,_BRIGHT_ROOM_IN_BROOKLYN",True,82004.0
102597,546.0,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,NaN,655.0,109.200000,Medium,32.0,"Long Island City , Queens",2015.0,BIG_STUDIO-ONE_STOP_FROM_MIDTOWN,True,45318.0
102598,1032.0,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,NaN,1238.0,NaN,High,20.0,"Upper West Side , Manhattan",NaN,585_SF_LUXURY_STUDIO,True,85656.0

In [80]:
#54 Change the data type of price to integer.

df['price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 102599 entries, 0 to 102598
Series name: price
Non-Null Count   Dtype
--------------   -----
102352 non-null  float64
dtypes: float64(1)
memory usage: 801.7 KB

In [81]:
df['price']=df['price'].astype('Int64')

In [82]:
#55. Create a new column showing price per night: price / minimum_nights.
df['ppn']=df['price']/df['minimum nights']

In [83]:
df['room type']

0            Private room
1         Entire home/apt
2            Private room
3         Entire home/apt
4         Entire home/apt
               ...
102594       Private room
102595       Private room
102596       Private room
102597    Entire home/apt
102598    Entire home/apt
Name: room type, Length: 102599, dtype: object

In [84]:
#56. Add a Boolean column indicating if the name contains the word “Luxury”.

df['lux']=df['NAME'].apply(lambda x:True if 'Luxury' in str(x) else False)

In [85]:
#57. Create a column for total estimated revenue = price * number_of_reviews.

df['tev']=df['price']*df['number of reviews']

In [86]:
#58. Replace “Entire home/apt” with “Whole Apartment” in the room_type column.

df['room type']=df['room type'].replace('Entire home/apt','Whole Apartment',regex=True)

In [87]:
#59 59. Change all city names to lowercase.

df['neighbourhood group']=df['neighbourhood group'].str.lower()

KeyError: 'neighbourhood group'

In [ ]:
#60. Split the listing name into two columns: first word and remaining words.


#df[['1st','2nd']]=df['NAME'].str.split(n=1,expand=True)

df['first_word'] = df['NAME'].apply(lambda x: str(x).split(' ')[0])
df['remaining_words'] = df['NAME'].apply(lambda x: ''.join(str(x).split(' ')[1:]))

In [ ]:
#61.  Find the average price for each room_type.

df.groupby('room type')['price'].mean()

In [ ]:
#62   Find the total number of listings per neighbourhood_group.

df.groupby('neighbourhood group').size()

In [88]:
#63Compute the maximum and minimum price for each city.
df.groupby('neighbourhood group')['price'].agg(['min','max'])

KeyError: 'neighbourhood group'

In [89]:
#64 Find which host has the maximum number of listings.

df['host name'].value_counts().head(1)

host name
Michael    881
Name: count, dtype: int64

In [90]:
#65 Calculate the mean availability_365 for each room_type.

df.groupby('room type')['availability 365'].mean()

room type
Hotel room         218.310345
Private room       137.557126
Shared room        172.666214
Whole Apartment    142.760376
Name: availability 365, dtype: float64

In [91]:
#66 Get the count of unique host names per city.

df.groupby('neighbourhood group')['host name'].nunique().reset_index(name='unique_host_count')

KeyError: 'neighbourhood group'

In [92]:
#67 For each city, find the average number of reviews.

df.groupby('neighbourhood group')['number of reviews'].mean()

KeyError: 'neighbourhood group'

In [93]:
#68.  Identify the city with the highest average price.

df.groupby('neighbourhood group')['price'].mean().sort_values(ascending=False).head(1)

KeyError: 'neighbourhood group'

In [94]:
#69.  Find the total revenue per host (price × number_of_reviews).

df['rev']=df['price']*df['number of reviews']

df.groupby('host name')['rev'].sum()

host name
#NAME?                       85596.0
'Cil                        198581.0
(Ari) HENRY LEE               7074.0
(Email hidden by Airbnb)     16197.0
(Mary) Haiy                 349680.0
                              ...
단비                               0.0
빈나                            1836.0
소정                             836.0
진                                0.0
현선                               0.0
Name: rev, Length: 13190, dtype: Float64

In [95]:
#70.  Group listings by region and show their average price.

df.groupby('neighbourhood group')['price'].mean()

KeyError: 'neighbourhood group'

In [96]:
#71.  Count how many listings exist for each minimum_nights value.

df.groupby('minimum nights').size()

minimum nights
-1223.0    1
-365.0     1
-200.0     1
-125.0     1
-12.0      1
          ..
 1000.0    2
 1250.0    1
 2645.0    1
 3455.0    1
 5645.0    1
Length: 153, dtype: int64

In [97]:
#72 Group by room_type and get the total number_of_reviews.

df.groupby('room type')['number of reviews'].sum()

room type
Hotel room            9679.0
Private room       1291669.0
Shared room          45368.0
Whole Apartment    1468059.0
Name: number of reviews, dtype: float64

In [98]:
# 73.  Find the top 5 hosts with the highest average price.

df.groupby('host name')['price'].mean().head().reset_index()

                  host name   price
0                    #NAME?   378.0
1                      'Cil   569.0
2           (Ari) HENRY LEE  1179.0
3  (Email hidden by Airbnb)   343.0
4               (Mary) Haiy   465.0

In [99]:
df

,price,id,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,...,lenName,location,year,NAME1,is_available,INRprice,ppn,lux,tev,rev
0,966,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,34.0,"Kensington , Brooklyn",2021.0,CLEAN_&_QUIET_APT_HOME_BY_THE_PARK,True,80178.0,96.6,False,8694.0,8694.0
1,142,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,21.0,"Midtown , Manhattan",2022.0,SKYLIT_MIDTOWN_CASTLE,True,11786.0,4.733333,False,6390.0,6390.0
2,620,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,...,35.0,"Harlem , Manhattan",NaN,THE_VILLAGE_OF_HARLEM....NEW_YORK_!,True,51460.0,206.666667,False,0.0,0.0
3,368,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,...,NaN,"Clinton Hill , Brooklyn",2019.0,NaN,True,30544.0,12.266667,False,99360.0,99360.0
4,204,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,48.0,"East Harlem , Manhattan",2018.0,ENTIRE_APT:_SPACIOUS_STUDIO/LOFT_BY_CENTRAL_PARK,True,16932.0,20.4,False,1836.0,1836.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,...,26.0,"Williamsburg , Brooklyn",NaN,SPARE_ROOM_IN_WILLIAMSBURG,True,70052.0,844.0,False,0.0,0.0
102595,837,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,...,29.0,"Morningside Heights , Manhattan",2015.0,BEST_LOCATION_NEAR_COLUMBIA_U,True,69471.0,837.0,False,837.0,837.0
102596,988,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,...,30.0,"Park Slope , Brooklyn",NaN,"COMFY,_BRIGHT_ROOM_IN_BROOKLYN",True,82004.0,329.333333,False,0.0,0.0
102597,546,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,...,32.0,"Long Island City , Queens",2015.0,BIG_STUDIO-ONE_STOP_FROM_MIDTOWN,True,45318.0,273.0,False,2730.0,2730.0
102598,1032,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,...,20.0,"Upper West Side , Manhattan",NaN,585_SF_LUXURY_STUDIO,True,85656.0,1032.0,True,0.0,0.0

In [100]:
df.columns

Index(['price', 'id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'region', 'neighbourhood', 'lat', 'long', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'a', 'ppr', 'Price_cat',
       'lenName', 'location', 'year', 'NAME1', 'is_available', 'INRprice',
       'ppn', 'lux', 'tev', 'rev'],
      dtype='object')

In [101]:
#74.  For each neighbourhood_group, find the listing with maximum price.

df.groupby('neighbourhood group')['price'].sum().sort_values().tail(1)

KeyError: 'neighbourhood group'

In [102]:
#75  Group listings by both city and room_type, and compute average price.

df.groupby(['neighbourhood group','room type'])['price'].mean()

KeyError: 'neighbourhood group'

In [103]:
#76 Get the standard deviation of price for each room_type.

df.groupby('room type')['price'].std()

room type
Hotel room         310.866487
Private room       331.332129
Shared room        338.701626
Whole Apartment    331.713213
Name: price, dtype: Float64

In [104]:
#77.  Find how many listings were reviewed in each year.

df['last review']=pd.to_datetime(df['last review'],errors='coerce')
df['year']=df['last review'].dt.year

df.groupby('year').size()

year
2012.0       26
2013.0       80
2014.0      246
2015.0     1874
2016.0     4316
2017.0     6601
2018.0    11455
2019.0    42931
2020.0     2063
2021.0     6740
2022.0    10369
2024.0        1
2025.0        1
2026.0        1
2040.0        1
2058.0        1
dtype: int64

In [111]:
#78.  Group listings by region and count how many have price> 100.

df[df['price']>100].groupby('region')['price'].count()

region
Bronx             2608
Brooklyn         39905
Manhattan        41720
Queens           12702
Staten Island      906
brookln              1
manhatan             1
Name: price, dtype: Int64

In [119]:
#79.  Identify which region has the most total reviews.

a=df.groupby('region')['number of reviews'].sum()
b=a.idxmax()
c=a.max()
b,c

('Brooklyn', 1190962.0)

In [120]:
#80.  For each host_id, calculate the total availability days.

df.groupby('host id')['availability 365'].sum()

host id
123600518        0.0
124039648        0.0
124472619        0.0
129756565      348.0
130349612      205.0
               ...
98758136270    117.0
98760968631      0.0
98762661810     71.0
98762683230     17.0
98763129024      0.0
Name: availability 365, Length: 102057, dtype: float64

In [105]:
df

,price,id,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,...,lenName,location,year,NAME1,is_available,INRprice,ppn,lux,tev,rev
0,966,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,34.0,"Kensington , Brooklyn",2021.0,CLEAN_&_QUIET_APT_HOME_BY_THE_PARK,True,80178.0,96.6,False,8694.0,8694.0
1,142,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,21.0,"Midtown , Manhattan",2022.0,SKYLIT_MIDTOWN_CASTLE,True,11786.0,4.733333,False,6390.0,6390.0
2,620,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,...,35.0,"Harlem , Manhattan",NaN,THE_VILLAGE_OF_HARLEM....NEW_YORK_!,True,51460.0,206.666667,False,0.0,0.0
3,368,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,...,NaN,"Clinton Hill , Brooklyn",2019.0,NaN,True,30544.0,12.266667,False,99360.0,99360.0
4,204,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,48.0,"East Harlem , Manhattan",2018.0,ENTIRE_APT:_SPACIOUS_STUDIO/LOFT_BY_CENTRAL_PARK,True,16932.0,20.4,False,1836.0,1836.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,...,26.0,"Williamsburg , Brooklyn",NaN,SPARE_ROOM_IN_WILLIAMSBURG,True,70052.0,844.0,False,0.0,0.0
102595,837,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,...,29.0,"Morningside Heights , Manhattan",2015.0,BEST_LOCATION_NEAR_COLUMBIA_U,True,69471.0,837.0,False,837.0,837.0
102596,988,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,...,30.0,"Park Slope , Brooklyn",NaN,"COMFY,_BRIGHT_ROOM_IN_BROOKLYN",True,82004.0,329.333333,False,0.0,0.0
102597,546,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,...,32.0,"Long Island City , Queens",2015.0,BIG_STUDIO-ONE_STOP_FROM_MIDTOWN,True,45318.0,273.0,False,2730.0,2730.0
102598,1032,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,...,20.0,"Upper West Side , Manhattan",NaN,585_SF_LUXURY_STUDIO,True,85656.0,1032.0,True,0.0,0.0

In [123]:
#81.Split the dataset into two DataFrames: one with price, one with reviews, then merge them back on id.

df_price=df[['id','price']]
df_review=df[['id','number of reviews']]

pd.merge(df_price,df_review,on='id',how='inner')

             id  price  number of reviews
0       1001254    966                9.0
1       1002102    142               45.0
2       1002403    620                0.0
3       1002755    368              270.0
4       1003689    204                9.0
...         ...    ...                ...
103676  6093542    988                0.0
103677  6094094    546                5.0
103678  6094094    546                5.0
103679  6094647   1032                0.0
103680  6094647   1032                0.0

[103681 rows x 3 columns]

In [127]:
#82.  Create a pivot table showing average price by city and room_type.

# Create a pivot table: average price by city and room_type
pivot_table = pd.pivot_table(df,
                             values='price',
                             index='region',
                             columns='room type',
                             aggfunc='mean')

pivot_table

room type      Hotel room  Private room  Shared room  Whole Apartment
region
Bronx                <NA>    634.710644    600.25641       620.232581
Brooklyn          736.125    625.870764   634.317073       626.896406
Manhattan          681.87    620.367881   632.522124        623.14757
Queens             433.25    631.813996    645.30663       627.030392
Staten Island        <NA>         603.5        715.6       642.192389
brookln              <NA>         580.0         <NA>             <NA>
manhatan             <NA>         460.0         <NA>             <NA>

In [131]:
#83 83.  Unstack a groupby result of room_type vs neighbourhood_group.

grouped=df.groupby(['region','room type']).size()

unstacked=grouped.unstack()
unstacked

room type      Hotel room  Private room  Shared room  Whole Apartment
region
Bronx                 NaN        1573.0        117.0           1022.0
Brooklyn              8.0       20434.0        825.0          20575.0
Manhattan           100.0       16312.0        907.0          26473.0
Queens                8.0        7751.0        362.0           5146.0
Staten Island         NaN         466.0         15.0            474.0
brookln               NaN           1.0          NaN              NaN
manhatan              NaN           1.0          NaN              NaN

In [135]:
#84.  Melt columns related to reviews into a long format.

melted_df = pd.melt(
    df,
    id_vars=['id', 'region'],  
    value_vars=['reviews per month', 'review rate number', 'number of reviews'],  
    var_name='review_metric',   
    value_name='value'          
)
melted_df

             id     region      review_metric  value
0       1001254   Brooklyn  reviews per month   0.21
1       1002102  Manhattan  reviews per month   0.38
2       1002403  Manhattan  reviews per month    NaN
3       1002755   Brooklyn  reviews per month   4.64
4       1003689  Manhattan  reviews per month   0.10
...         ...        ...                ...    ...
307792  6092437   Brooklyn  number of reviews   0.00
307793  6092990  Manhattan  number of reviews   1.00
307794  6093542   Brooklyn  number of reviews   0.00
307795  6094094     Queens  number of reviews   5.00
307796  6094647  Manhattan  number of reviews   0.00

[307797 rows x 4 columns]

In [136]:
#85.  Concatenate two subsets of listings (top 10 expensive + top 10 cheapest).

exp=df.sort_values(by='price').tail(10)
che=df.sort_values(by='price').head(10)

pd.concat([exp,che])

,price,id,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,...,lenName,location,year,NAME1,is_available,INRprice,ppn,lux,tev,rev
97775,<NA>,55002469,"Studio at Upper East Side Manhattan, New York",59846872035,unconfirmed,Тest,Manhattan,Upper East Side,40.777130,-73.95309,...,45.0,"Upper East Side , Manhattan",2018.0,"STUDIO_AT_UPPER_EAST_SIDE_MANHATTAN,_NEW_YORK",False,NaN,<NA>,False,<NA>,<NA>
97776,<NA>,55003021,Spacious Harlem Room,11251026866,verified,Silvia,Manhattan,Harlem,40.829230,-73.93764,...,20.0,"Harlem , Manhattan",2019.0,SPACIOUS_HARLEM_ROOM,True,NaN,<NA>,False,<NA>,<NA>
97777,<NA>,55003573,Flatiron Penthouse,77242696688,unconfirmed,Ben,Manhattan,Gramercy,40.738010,-73.98815,...,18.0,"Gramercy , Manhattan",2018.0,FLATIRON_PENTHOUSE,False,NaN,<NA>,False,<NA>,<NA>
97778,<NA>,55004125,New York Condominium,64973756767,unconfirmed,Ken,Manhattan,SoHo,40.720600,-74.00330,...,20.0,"SoHo , Manhattan",2018.0,NEW_YORK_CONDOMINIUM,True,NaN,<NA>,False,<NA>,<NA>
102045,<NA>,57360790,Private Bedroom in Rego Park / Forest Hills,15978912806,unconfirmed,NaN,Queens,Rego Park,40.724600,-73.85688,...,43.0,"Rego Park , Queens",NaN,PRIVATE_BEDROOM_IN_REGO_PARK_/_FOREST_HILLS,False,NaN,<NA>,False,<NA>,<NA>
102046,<NA>,57361342,Sunny budget friendly room in Bushwick,29964876857,verified,NaN,Brooklyn,Bushwick,40.693700,-73.91006,...,38.0,"Bushwick , Brooklyn",2018.0,SUNNY_BUDGET_FRIENDLY_ROOM_IN_BUSHWICK,False,NaN,<NA>,False,<NA>,<NA>
102047,<NA>,57361894,"Cozy Apartment on Bedford Ave, Brooklyn",92852058426,unconfirmed,NaN,Brooklyn,Williamsburg,40.712840,-73.96284,...,39.0,"Williamsburg , Brooklyn",2018.0,"COZY_APARTMENT_ON_BEDFORD_AVE,_BROOKLYN",False,NaN,<NA>,False,<NA>,<NA>
102048,<NA>,57362446,Your 1 bedroom home away from home!,95572379802,verified,NaN,Manhattan,Upper West Side,40.795630,-73.97634,...,35.0,"Upper West Side , Manhattan",2019.0,YOUR_1_BEDROOM_HOME_AWAY_FROM_HOME!,True,NaN,<NA>,False,<NA>,<NA>
102049,<NA>,57362999,MASTER Cozy Bedroom Queen size 2 blocks Timesq...,80154173698,verified,NaN,Manhattan,Hell's Kitchen,40.761250,-73.98945,...,50.0,"Hell's Kitchen , Manhattan",2019.0,MASTER_COZY_BEDROOM_QUEEN_SIZE_2_BLOCKS_TIMESQ...,False,NaN,<NA>,False,<NA>,<NA>
102050,<NA>,57363551,Sunny Brownstone Studio in BedStuy Brooklyn,11145329848,unconfirmed,Jamal,Brooklyn,Bedford-Stuyvesant,40.682210,-73.94618,...,43.0,"Bedford-Stuyvesant , Brooklyn",2019.0,SUNNY_BROWNSTONE_STUDIO_IN_BEDSTUY_BROOKLYN,True,NaN,<NA>,False,<NA>,<NA>
24254,50,14396820,NEWLY Renovated Private 2 Bed Apt on 1 st Floor..,96466051733,unconfirmed,Oscar,Brooklyn,Bedford-Stuyvesant,40.682680,-73.94548,...,49.0,"Bedford-Stuyvesant , Brooklyn",2019.0,NEWLY_RENOVATED_PRIVATE_2_BED_APT_ON_1_ST_FLOOR..,True,4150.0,12.5,False,1650.0,1650.0
61234,50,34820874,A private humble abode for you,4833155663,unconfirmed,Sandra,Brooklyn,Canarsie,40.640300,-73.89549,...,30.0,"Canarsie , Brooklyn",2021.0,A_PRIVATE_HUMBLE_ABODE_FOR_YOU,True,4150.0,25.0,False,6800.0,6800.0
69032,50,39127710,"Cozy basement with open design, separate entrance",58787926973,verified,Shanika,Queens,St. Albans,40.701030,-73.75260,...,49.0,"St. Albans , Queens",2022.0,"COZY_BASEMENT_WITH_OPEN_DESIGN,_SEPARATE_ENTRANCE",True,4150.0,50.0,False,1100.0,1100.0
45551,50,26159153,Comfortable double room with balcony(舒适双人房带阳台),82834973843,unconfirmed,H Ai,Queens,Flushing,40.761530,-73.80726,...,46.0,"Flushing , Queens",NaN,COMFORTABLE_DOUBLE_ROOM_WITH_BALCONY(舒适双人房带阳台),True,4150.0,50.0,False,0.0,0.0
60981,50,34681142,Charming Greenwich Village Artist’s Haven,71941078154,verified,Kate,Manhattan,Greenwich Village,40.732350,-73.99791,...,41.0,"Greenwich Village , Manhattan",2021.0,CHARMING_GREENWICH_VILLAGE_ARTIST’S_HAVEN,True,4150.0,1.666667,False,900.0,900.0
45860,50,26329814,Pvt studio with pvt entrance&pvt bathroom near...,44535559262,verified,Safain,Queens,Ozone Park,40.675650,-73.84677,...,50.0,"Ozone Park , Queens",2019.0,PVT_STUDIO_WITH_PVT_ENTRANCE&PVT_BATHROOM_NEAR...,True,4150.0,16.666667,False,200.0,200.0
86298,50,48663721,SUNNY APT Best location In Williamsburg!!!!!,13298174979,unconfirmed,Juan,Brooklyn,Williamsburg,40.710240,-73.96081,...,44.0,"Williamsburg , Brooklyn",2019.0,SUNNY_APT_BEST_LOCATION_IN_WILLIAMSBURG!!!!!,True,4150.0,25.0,False,6000.0,6000.0
62754,50,35660370,1 Bed in a 4-Bed Mixed Dorm with Private Bath...,54281995181,unconfirmed,The Local,Queens,Long Island City,40.749565,-73.94783,...,50.0,"Long Island City , Queens",2021.0,1_BED_IN_A_4-BED_MIXED__DORM_WITH_PRIVATE_BATH...,True,4150.0,50.0,False,450.0,450.0
11730,50,7479815,"Gorgeous, Cozy Studio w/ Projector!",40963832458,verified,Cathy,Manhattan,East Village,40.728100,-73.97952,...,35.0,"East Village , Manhattan",2018.0,"GORGEOUS,_COZY_STUDIO_W/_PROJECTOR!",True,4150.0,10.0,False,150.0,150.0
56916,50,32436043,twin bed in sharing room near Grand Central,3926079443,unconfirmed,Mizue,Manhattan,Murray Hill,40.750370,-73.97820,...,43.0,"Murray Hill , Manhattan",2022.0,TWIN_BED_IN_SHARING_ROOM_NEAR_GRAND_CENTRAL,True,4150.0,8.333333,False,8700.0,8700.0

In [138]:
#86.  Merge two DataFrames: one with host info, one with listing info (based on host_id).

a=df[['host id','host_identity_verified','host name']]
b=df[['host id','NAME','region','neighbourhood']]

pd.merge(a,b,on='host id',how='inner')

,host id,host_identity_verified,host name,NAME,region,neighbourhood
0,80014485718,unconfirmed,Madaline,Clean & quiet apt home by the park,Brooklyn,Kensington
1,52335172823,verified,Jenna,Skylit Midtown Castle,Manhattan,Midtown
2,78829239556,NaN,Elise,THE VILLAGE OF HARLEM....NEW YORK !,Manhattan,Harlem
3,85098326012,unconfirmed,Garry,NaN,Brooklyn,Clinton Hill
4,92037596077,verified,Lyndon,Entire Apt: Spacious Studio/Loft by central park,Manhattan,East Harlem
...,...,...,...,...,...,...
103678,69050334417,unconfirmed,Megan,"Comfy, bright room in Brooklyn",Brooklyn,Park Slope
103679,11160591270,unconfirmed,Christopher,Big Studio-One Stop from Midtown,Queens,Long Island City
103680,11160591270,unconfirmed,Christopher,Big Studio-One Stop from Midtown,Queens,Long Island City
103681,68170633372,unconfirmed,Rebecca,585 sf Luxury Studio,Manhattan,Upper West Side
103682,68170633372,unconfirmed,Rebecca,585 sf Luxury Studio,Manhattan,Upper West Side

In [139]:
df.columns

Index(['price', 'id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'region', 'neighbourhood', 'lat', 'long', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'a', 'ppr', 'Price_cat',
       'lenName', 'location', 'year', 'NAME1', 'is_available', 'INRprice',
       'ppn', 'lux', 'tev', 'rev'],
      dtype='object')

In [142]:
#87.  Create a MultiIndex DataFrame grouped by city and region.

df.groupby(['region', 'neighbourhood']).agg({
    'price': 'mean',
    'number of reviews': 'sum'
})

                                  price  number of reviews
region        neighbourhood
Bronx         Allerton        636.34375             5492.0
              Baychester          524.0             1138.0
              Belmont        672.488889              865.0
              Bronxdale      574.170213             1536.0
              Castle Hill    485.181818              607.0
...                                 ...                ...
Staten Island Westerleigh         477.2              100.0
              Willowbrook         638.0               46.0
              Woodrow        709.333333               21.0
brookln       South Slope         580.0              167.0
manhatan      Chelsea             460.0              260.0

[226 rows x 2 columns]

In [ ]:
#88.  Sort index after grouping by multiple columns.